/**
 * Internal dependencies
 */

export const REVENUES_LOADING = 'REVENUES_LOADING';
export const REVENUES_LOADED = 'REVENUES_LOADED';
export const REVENUES_FAILED = 'REVENUES_FAILED';
export const REVENUES_SET_SELECTED = 'REVENUES_SET_SELECTED';
export const REVENUES_SET_ALL_SELECTED = 'REVENUES_SET_ALL_SELECTED';
export const REVENUES_ITEM_SAVING = 'REVENUES_ITEM_SAVING';
export const REVENUES_ITEM_FAILED = 'REVENUES_ITEM_FAILED';
export const REVENUES_ITEM_SAVED = 'REVENUES_ITEM_SAVED';
export const REVENUES_DISPLAY_SET = 'REVENUES_DISPLAY_SET';
