/**
 * Internal dependencies
 */

export const BILLS_LOADING = 'BILLS_LOADING';
export const BILLS_LOADED = 'BILLS_LOADED';
export const BILLS_FAILED = 'BILLS_FAILED';
export const BILLS_SET_SELECTED = 'BILLS_SET_SELECTED';
export const BILLS_SET_ALL_SELECTED = 'BILLS_SET_ALL_SELECTED';
export const BILLS_ITEM_SAVING = 'BILLS_ITEM_SAVING';
export const BILLS_ITEM_FAILED = 'BILLS_ITEM_FAILED';
export const BILLS_ITEM_SAVED = 'BILLS_ITEM_SAVED';
export const BILLS_DISPLAY_SET = 'BILLS_DISPLAY_SET';
