/**
 * Internal dependencies
 */

export const TRANSFERS_LOADING = 'TRANSFERS_LOADING';
export const TRANSFERS_LOADED = 'TRANSFERS_LOADED';
export const TRANSFERS_FAILED = 'TRANSFERS_FAILED';
export const TRANSFERS_SET_SELECTED = 'TRANSFERS_SET_SELECTED';
export const TRANSFERS_SET_ALL_SELECTED = 'TRANSFERS_SET_ALL_SELECTED';
export const TRANSFERS_ITEM_SAVING = 'TRANSFERS_ITEM_SAVING';
export const TRANSFERS_ITEM_FAILED = 'TRANSFERS_ITEM_FAILED';
export const TRANSFERS_ITEM_SAVED = 'TRANSFERS_ITEM_SAVED';
export const TRANSFERS_ITEM_ADDED = 'TRANSFERS_ITEM_ADDED';
