export const ACTION_TYPES = {
	RECEIVE_COLLECTION: 'RECEIVE_COLLECTION',
	RESET_COLLECTION: 'RESET_COLLECTION',
	DELETE_COLLECTION_ITEM: 'DELETE_COLLECTION_ITEM',
	UPDATE_COLLECTION_ITEM: 'UPDATE_COLLECTION_ITEM',
	ERROR: 'ERROR',
	RECEIVE_LAST_MODIFIED: 'RECEIVE_LAST_MODIFIED',
	INVALIDATE_RESOLUTION_FOR_STORE: 'INVALIDATE_RESOLUTION_FOR_STORE',
};
