/**
 * Internal dependencies
 */

export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const ACCOUNTS_LOADED = 'ACCOUNTS_LOADED';
export const ACCOUNTS_FAILED = 'ACCOUNTS_FAILED';
export const ACCOUNTS_SET_SELECTED = 'ACCOUNTS_SET_SELECTED';
export const ACCOUNTS_SET_ALL_SELECTED = 'ACCOUNTS_SET_ALL_SELECTED';
export const ACCOUNTS_ITEM_SAVING = 'ACCOUNTS_ITEM_SAVING';
export const ACCOUNTS_ITEM_FAILED = 'ACCOUNTS_ITEM_FAILED';
export const ACCOUNTS_ITEM_SAVED = 'ACCOUNTS_ITEM_SAVED';
export const ACCOUNTS_ITEM_ADDED = 'ACCOUNTS_ITEM_ADDED';
