export const ACTION_TYPES = {
	TABLE_LOADING: "TABLE_LOADING",
	TABLE_LOADED: "TABLE_LOADED",
	TABLE_FAILED: "TABLE_FAILED",
	TABLE_RESET: 'TABLE_RESET',
	TABLE_ITEM_SELECTED: 'TABLE_ITEM_SELECTED',
	TABLE_ALL_SELECTED: 'TABLE_ALL_SELECTED',

	RECEIVE_SETTINGS: "RECEIVE_SETTINGS",

	SET_QUERY: "SET_QUERY",
	SET_QUERIES: "SET_QUERIES",
	RESET_QUERIES: "RESET_QUERIES",
};


