/**
 * Internal dependencies
 */

export const TAXRATES_LOADING = 'TAXRATES_LOADING';
export const TAXRATES_LOADED = 'TAXRATES_LOADED';
export const TAXRATES_FAILED = 'TAXRATES_FAILED';
export const TAXRATES_SET_SELECTED = 'TAXRATES_SET_SELECTED';
export const TAXRATES_SET_ALL_SELECTED = 'TAXRATES_SET_ALL_SELECTED';
export const TAXRATES_ITEM_SAVING = 'TAXRATES_ITEM_SAVING';
export const TAXRATES_ITEM_FAILED = 'TAXRATES_ITEM_FAILED';
export const TAXRATES_ITEM_SAVED = 'TAXRATES_ITEM_SAVED';
export const TAXRATES_DISPLAY_SET = 'TAXRATES_DISPLAY_SET';
