/**
 * Internal dependencies
 */

export const INVOICES_LOADING = 'INVOICES_LOADING';
export const INVOICES_LOADED = 'INVOICES_LOADED';
export const INVOICES_FAILED = 'INVOICES_FAILED';
export const INVOICES_SET_SELECTED = 'INVOICES_SET_SELECTED';
export const INVOICES_SET_ALL_SELECTED = 'INVOICES_SET_ALL_SELECTED';
export const INVOICES_ITEM_SAVING = 'INVOICES_ITEM_SAVING';
export const INVOICES_ITEM_FAILED = 'INVOICES_ITEM_FAILED';
export const INVOICES_ITEM_SAVED = 'INVOICES_ITEM_SAVED';
export const INVOICES_DISPLAY_SET = 'INVOICES_DISPLAY_SET';
