/**
 * Internal dependencies
 */

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';
export const CATEGORIES_SET_SELECTED = 'CATEGORIES_SET_SELECTED';
export const CATEGORIES_SET_ALL_SELECTED = 'CATEGORIES_SET_ALL_SELECTED';
export const CATEGORIES_ITEM_SAVING = 'CATEGORIES_ITEM_SAVING';
export const CATEGORIES_ITEM_FAILED = 'CATEGORIES_ITEM_FAILED';
export const CATEGORIES_ITEM_SAVED = 'CATEGORIES_ITEM_SAVED';
export const CATEGORIES_DISPLAY_SET = 'CATEGORIES_DISPLAY_SET';
