<?php

namespace EverAccounting\Gateways;

use EverAccounting\Abstracts\Gateway;

/**
 * Class Two_Checkout
 * @package EverAccounting\Gateways
 */
class Two_Checkout extends Gateway {


	/**
	 * Two_Checkout constructor.
	 */
	public function __construct() {
		$this->id    = '2checkout';
		$this->title = __( '2Checkout', 'wp-ever-accounting' );
		parent::__construct();
	}


	public function settings_fields() {
		return parent::settings_fields(); // TODO: Change the autogenerated stub
	}

}
