export const currencies = {
	AED: {
		code: "AED",
		symbol: 'د.إ.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	AFN: {
		code: "AFN",
		symbol: '؋',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	ALL: {
		code: "ALL",
		symbol: 'Lek',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	AMD: {
		code: "AMD",
		symbol: '֏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	ANG: {
		code: "ANG",
		symbol: 'ƒ',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	AOA: {
		code: "AOA",
		symbol: 'Kz',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	ARS: {
		code: "ARS",
		symbol: '$',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	AUD: {
		code: "AUD",
		symbol: 'A$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	AWG: {
		code: "AWG",
		symbol: 'ƒ',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	AZN: {
		code: "AZN",
		symbol: '₼',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	BAM: {
		code: "BAM",
		symbol: 'КМ',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	BBD: {
		code: "BBD",
		symbol: 'Bds$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	BDT: {
		code: "BDT",
		symbol: '৳',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	BGN: {
		code: "BGN",
		symbol: 'лв.',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	BHD: {
		code: "BHD",
		symbol: 'د.ب.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 3,
	},
	BIF: {
		code: "BIF",
		symbol: 'FBu',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	BMD: {
		code: "BMD",
		symbol: '$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	BND: {
		code: "BND",
		symbol: '$',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 0,
	},
	BOB: {
		code: "BOB",
		symbol: 'Bs',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	BRL: {
		code: "BRL",
		symbol: 'R$',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	BSD: {
		code: "BSD",
		symbol: '$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	BTC: {
		code: "BTC",
		symbol: 'Ƀ',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	BTN: {
		code: "BTN",
		symbol: 'Nu.',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 1,
	},
	BWP: {
		code: "BWP",
		symbol: 'P',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	BYR: {
		code: "BYR",
		symbol: 'р.',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	BZD: {
		code: "BZD",
		symbol: 'BZ$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	CAD: {
		code: "CAD",
		symbol: 'C$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	CDF: {
		code: "CDF",
		symbol: 'FC',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	CHF: {
		code: "CHF",
		symbol: 'CHF',
		thousandSeparator: "'",
		decimalSeparator: '.',
		precision: 2,
	},
	CLP: {
		code: "CLP",
		symbol: '$',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	CNY: {
		code: "CNY",
		symbol: '¥',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	COP: {
		code: "COP",
		symbol: '$',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	CRC: {
		code: "CRC",
		symbol: '₡',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	CUC: {
		code: "CUC",
		symbol: 'CUC',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	CUP: {
		code: "CUP",
		symbol: '$MN',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	CVE: {
		code: "CVE",
		symbol: '$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	CZK: {
		code: "CZK",
		symbol: 'Kč',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	DJF: {
		code: "DJF",
		symbol: 'Fdj',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	DKK: {
		code: "DKK",
		symbol: 'kr.',
		thousandSeparator: '',
		decimalSeparator: ',',
		precision: 2,
	},
	DOP: {
		code: "DOP",
		symbol: 'RD$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	DZD: {
		code: "DZD",
		symbol: 'د.ج.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	EGP: {
		code: "EGP",
		symbol: 'ج.م.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	ERN: {
		code: "ERN",
		symbol: 'Nfk',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	ETB: {
		code: "ETB",
		symbol: 'ETB',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	EUR: {
		code: "EUR",
		symbol: '€',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	FJD: {
		code: "FJD",
		symbol: 'FJ$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	FKP: {
		code: "FKP",
		symbol: '£',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	GBP: {
		code: "GBP",
		symbol: '£',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	GEL: {
		code: "GEL",
		symbol: 'Lari',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	GHS: {
		code: "GHS",
		symbol: '₵',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	GIP: {
		code: "GIP",
		symbol: '£',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	GMD: {
		code: "GMD",
		symbol: 'D',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	GNF: {
		code: "GNF",
		symbol: 'FG',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	GTQ: {
		code: "GTQ",
		symbol: 'Q',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	GYD: {
		code: "GYD",
		symbol: 'G$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	HKD: {
		code: "HKD",
		symbol: 'HK$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	HNL: {
		code: "HNL",
		symbol: 'L.',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	HRK: {
		code: "HRK",
		symbol: 'kn',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	HTG: {
		code: "HTG",
		symbol: 'G',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	HUF: {
		code: "HUF",
		symbol: 'Ft',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 0,
	},
	IDR: {
		code: "IDR",
		symbol: 'Rp',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 0,
	},
	ILS: {
		code: "ILS",
		symbol: '₪',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	INR: {
		code: "INR",
		symbol: '₹',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	IQD: {
		code: "IQD",
		symbol: 'د.ع.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	IRR: {
		code: "IRR",
		symbol: '﷼',
		thousandSeparator: ',',
		decimalSeparator: '/',
		precision: 2,
	},
	ISK: {
		code: "ISK",
		symbol: 'kr.',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 0,
	},
	JMD: {
		code: "JMD",
		symbol: 'J$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	JOD: {
		code: "JOD",
		symbol: 'د.ا.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 3,
	},
	JPY: {
		code: "JPY",
		symbol: '¥',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	KES: {
		code: "KES",
		symbol: 'S',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	KGS: {
		code: "KGS",
		symbol: 'сом',
		thousandSeparator: ' ',
		decimalSeparator: '-',
		precision: 2,
	},
	KHR: {
		code: "KHR",
		symbol: '៛',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	KMF: {
		code: "KMF",
		symbol: 'CF',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	KPW: {
		code: "KPW",
		symbol: '₩',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	KRW: {
		code: "KRW",
		symbol: '₩',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	KWD: {
		code: "KWD",
		symbol: 'د.ك.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 3,
	},
	KYD: {
		code: "KYD",
		symbol: '$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	KZT: {
		code: "KZT",
		symbol: '₸',
		thousandSeparator: ' ',
		decimalSeparator: '-',
		precision: 2,
	},
	LAK: {
		code: "LAK",
		symbol: '₭',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	LBP: {
		code: "LBP",
		symbol: 'ل.ل.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	LKR: {
		code: "LKR",
		symbol: '₨',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	LRD: {
		code: "LRD",
		symbol: 'L$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	LSL: {
		code: "LSL",
		symbol: 'M',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	LYD: {
		code: "LYD",
		symbol: 'د.ل.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 3,
	},
	MAD: {
		code: "MAD",
		symbol: 'د.م.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MDL: {
		code: "MDL",
		symbol: 'lei',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MGA: {
		code: "MGA",
		symbol: 'Ar',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	MKD: {
		code: "MKD",
		symbol: 'ден.',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	MMK: {
		code: "MMK",
		symbol: 'K',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MNT: {
		code: "MNT",
		symbol: '₮',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	MOP: {
		code: "MOP",
		symbol: 'MOP$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MRO: {
		code: "MRO",
		symbol: 'UM',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MTL: {
		code: "MTL",
		symbol: '₤',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MUR: {
		code: "MUR",
		symbol: '₨',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MVR: {
		code: "MVR",
		symbol: 'MVR',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 1,
	},
	MWK: {
		code: "MWK",
		symbol: 'MK',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MXN: {
		code: "MXN",
		symbol: 'MX$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MYR: {
		code: "MYR",
		symbol: 'RM',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	MZN: {
		code: "MZN",
		symbol: 'MT',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	NAD: {
		code: "NAD",
		symbol: 'N$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	NGN: {
		code: "NGN",
		symbol: '₦',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	NIO: {
		code: "NIO",
		symbol: 'C$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	NOK: {
		code: "NOK",
		symbol: 'kr',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	NPR: {
		code: "NPR",
		symbol: '₨',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	NZD: {
		code: "NZD",
		symbol: 'NZ$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	OMR: {
		code: "OMR",
		symbol: '﷼',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 3,
	},
	PAB: {
		code: "PAB",
		symbol: 'B/.',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	PEN: {
		code: "PEN",
		symbol: 'S/.',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	PGK: {
		code: "PGK",
		symbol: 'K',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	PHP: {
		code: "PHP",
		symbol: '₱',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	PKR: {
		code: "PKR",
		symbol: '₨',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	PLN: {
		code: "PLN",
		symbol: 'zł',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	PYG: {
		code: "PYG",
		symbol: '₲',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	QAR: {
		code: "QAR",
		symbol: '﷼',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	RON: {
		code: "RON",
		symbol: 'lei',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	RSD: {
		code: "RSD",
		symbol: 'Дин.',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	RUB: {
		code: "RUB",
		symbol: '₽',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	RWF: {
		code: "RWF",
		symbol: 'RWF',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	SAR: {
		code: "SAR",
		symbol: '﷼',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SBD: {
		code: "SBD",
		symbol: 'S$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SCR: {
		code: "SCR",
		symbol: '₨',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SDD: {
		code: "SDD",
		symbol: 'LSd',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SDG: {
		code: "SDG",
		symbol: '£‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SEK: {
		code: "SEK",
		symbol: 'kr',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SGD: {
		code: "SGD",
		symbol: 'S$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SHP: {
		code: "SHP",
		symbol: '£',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SLL: {
		code: "SLL",
		symbol: 'Le',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SOS: {
		code: "SOS",
		symbol: 'S',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SRD: {
		code: "SRD",
		symbol: '$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	STD: {
		code: "STD",
		symbol: 'Db',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SVC: {
		code: "SVC",
		symbol: '₡',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SYP: {
		code: "SYP",
		symbol: '£',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	SZL: {
		code: "SZL",
		symbol: 'E',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	THB: {
		code: "THB",
		symbol: '฿',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	TJS: {
		code: "TJS",
		symbol: 'TJS',
		thousandSeparator: ' ',
		decimalSeparator: ';',
		precision: 2,
	},
	TMT: {
		code: "TMT",
		symbol: 'm',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 0,
	},
	TND: {
		code: "TND",
		symbol: 'د.ت.‏',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 3,
	},
	TOP: {
		code: "TOP",
		symbol: 'T$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	TRY: {
		code: "TRY",
		symbol: 'TL',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	TTD: {
		code: "TTD",
		symbol: 'TT$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	TVD: {
		code: "TVD",
		symbol: '$T',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	TWD: {
		code: "TWD",
		symbol: 'NT$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	TZS: {
		code: "TZS",
		symbol: 'TSh',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	UAH: {
		code: "UAH",
		symbol: '₴',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	UGX: {
		code: "UGX",
		symbol: 'USh',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	USD: {
		code: "USD",
		symbol: '$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	UYU: {
		code: "UYU",
		symbol: '$U',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	UZS: {
		code: "UZS",
		symbol: 'сўм',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	VEB: {
		code: "VEB",
		symbol: 'Bs.',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	VEF: {
		code: "VEF",
		symbol: 'Bs. F.',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 2,
	},
	VND: {
		code: "VND",
		symbol: '₫',
		thousandSeparator: '.',
		decimalSeparator: ',',
		precision: 1,
	},
	VUV: {
		code: "VUV",
		symbol: 'VT',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 0,
	},
	WST: {
		code: "WST",
		symbol: 'WS$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	XAF: {
		code: "XAF",
		symbol: 'F',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	XCD: {
		code: "XCD",
		symbol: '$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	XOF: {
		code: "XOF",
		symbol: 'F',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	XPF: {
		code: "XPF",
		symbol: 'F',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	YER: {
		code: "YER",
		symbol: '﷼',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	ZAR: {
		code: "ZAR",
		symbol: 'R',
		thousandSeparator: ' ',
		decimalSeparator: ',',
		precision: 2,
	},
	ZMW: {
		code: "ZMW",
		symbol: 'ZK',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
	WON: {
		code: "WON",
		symbol: '₩',
		thousandSeparator: ',',
		decimalSeparator: '.',
		precision: 2,
	},
};

/**
 * Returns currency defaults.
 *
 * @param   {string} code      currency code
 * @returns {?object}          currency defaults
 */
export function getCurrencyData(code) {
	const defaultCurrency = {
		symbol: '$',
		thousandSeparator: ',',
		decimalSeparator: '.',
		position:'before',
		precision: 2,
	};

	return currencies[code] || defaultCurrency;
}
