export const currencies = {
	AED: {
		symbol: 'د.إ.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	AFN: {
		symbol: '؋',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	ALL: {
		symbol: 'Lek',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	AMD: {
		symbol: '֏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	ANG: {
		symbol: 'ƒ',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	AOA: {
		symbol: 'Kz',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	ARS: {
		symbol: '$',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	AUD: {
		symbol: 'A$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	AWG: {
		symbol: 'ƒ',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	AZN: {
		symbol: '₼',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	BAM: {
		symbol: 'КМ',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	BBD: {
		symbol: 'Bds$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	BDT: {
		symbol: '৳',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	BGN: {
		symbol: 'лв.',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	BHD: {
		symbol: 'د.ب.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 3,
	},
	BIF: {
		symbol: 'FBu',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	BMD: {
		symbol: '$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	BND: {
		symbol: '$',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 0,
	},
	BOB: {
		symbol: 'Bs',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	BRL: {
		symbol: 'R$',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	BSD: {
		symbol: '$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	BTC: {
		symbol: 'Ƀ',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	BTN: {
		symbol: 'Nu.',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 1,
	},
	BWP: {
		symbol: 'P',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	BYR: {
		symbol: 'р.',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	BZD: {
		symbol: 'BZ$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	CAD: {
		symbol: 'C$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	CDF: {
		symbol: 'FC',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	CHF: {
		symbol: 'CHF',
		thousands_separator: "'",
		decimal_mark: '.',
		precision: 2,
	},
	CLP: {
		symbol: '$',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	CNY: {
		symbol: '¥',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	COP: {
		symbol: '$',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	CRC: {
		symbol: '₡',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	CUC: {
		symbol: 'CUC',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	CUP: {
		symbol: '$MN',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	CVE: {
		symbol: '$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	CZK: {
		symbol: 'Kč',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	DJF: {
		symbol: 'Fdj',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	DKK: {
		symbol: 'kr.',
		thousands_separator: '',
		decimal_mark: ',',
		precision: 2,
	},
	DOP: {
		symbol: 'RD$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	DZD: {
		symbol: 'د.ج.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	EGP: {
		symbol: 'ج.م.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	ERN: {
		symbol: 'Nfk',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	ETB: {
		symbol: 'ETB',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	EUR: {
		symbol: '€',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	FJD: {
		symbol: 'FJ$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	FKP: {
		symbol: '£',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	GBP: {
		symbol: '£',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	GEL: {
		symbol: 'Lari',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	GHS: {
		symbol: '₵',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	GIP: {
		symbol: '£',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	GMD: {
		symbol: 'D',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	GNF: {
		symbol: 'FG',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	GTQ: {
		symbol: 'Q',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	GYD: {
		symbol: 'G$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	HKD: {
		symbol: 'HK$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	HNL: {
		symbol: 'L.',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	HRK: {
		symbol: 'kn',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	HTG: {
		symbol: 'G',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	HUF: {
		symbol: 'Ft',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 0,
	},
	IDR: {
		symbol: 'Rp',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 0,
	},
	ILS: {
		symbol: '₪',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	INR: {
		symbol: '₹',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	IQD: {
		symbol: 'د.ع.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	IRR: {
		symbol: '﷼',
		thousands_separator: ',',
		decimal_mark: '/',
		precision: 2,
	},
	ISK: {
		symbol: 'kr.',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 0,
	},
	JMD: {
		symbol: 'J$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	JOD: {
		symbol: 'د.ا.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 3,
	},
	JPY: {
		symbol: '¥',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	KES: {
		symbol: 'S',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	KGS: {
		symbol: 'сом',
		thousands_separator: ' ',
		decimal_mark: '-',
		precision: 2,
	},
	KHR: {
		symbol: '៛',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	KMF: {
		symbol: 'CF',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	KPW: {
		symbol: '₩',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	KRW: {
		symbol: '₩',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	KWD: {
		symbol: 'د.ك.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 3,
	},
	KYD: {
		symbol: '$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	KZT: {
		symbol: '₸',
		thousands_separator: ' ',
		decimal_mark: '-',
		precision: 2,
	},
	LAK: {
		symbol: '₭',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	LBP: {
		symbol: 'ل.ل.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	LKR: {
		symbol: '₨',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	LRD: {
		symbol: 'L$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	LSL: {
		symbol: 'M',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	LYD: {
		symbol: 'د.ل.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 3,
	},
	MAD: {
		symbol: 'د.م.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MDL: {
		symbol: 'lei',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MGA: {
		symbol: 'Ar',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	MKD: {
		symbol: 'ден.',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	MMK: {
		symbol: 'K',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MNT: {
		symbol: '₮',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	MOP: {
		symbol: 'MOP$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MRO: {
		symbol: 'UM',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MTL: {
		symbol: '₤',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MUR: {
		symbol: '₨',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MVR: {
		symbol: 'MVR',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 1,
	},
	MWK: {
		symbol: 'MK',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MXN: {
		symbol: 'MX$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MYR: {
		symbol: 'RM',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	MZN: {
		symbol: 'MT',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	NAD: {
		symbol: 'N$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	NGN: {
		symbol: '₦',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	NIO: {
		symbol: 'C$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	NOK: {
		symbol: 'kr',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	NPR: {
		symbol: '₨',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	NZD: {
		symbol: 'NZ$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	OMR: {
		symbol: '﷼',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 3,
	},
	PAB: {
		symbol: 'B/.',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	PEN: {
		symbol: 'S/.',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	PGK: {
		symbol: 'K',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	PHP: {
		symbol: '₱',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	PKR: {
		symbol: '₨',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	PLN: {
		symbol: 'zł',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	PYG: {
		symbol: '₲',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	QAR: {
		symbol: '﷼',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	RON: {
		symbol: 'lei',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	RSD: {
		symbol: 'Дин.',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	RUB: {
		symbol: '₽',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	RWF: {
		symbol: 'RWF',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	SAR: {
		symbol: '﷼',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SBD: {
		symbol: 'S$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SCR: {
		symbol: '₨',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SDD: {
		symbol: 'LSd',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SDG: {
		symbol: '£‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SEK: {
		symbol: 'kr',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SGD: {
		symbol: 'S$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SHP: {
		symbol: '£',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SLL: {
		symbol: 'Le',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SOS: {
		symbol: 'S',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SRD: {
		symbol: '$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	STD: {
		symbol: 'Db',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SVC: {
		symbol: '₡',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SYP: {
		symbol: '£',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	SZL: {
		symbol: 'E',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	THB: {
		symbol: '฿',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	TJS: {
		symbol: 'TJS',
		thousands_separator: ' ',
		decimal_mark: ';',
		precision: 2,
	},
	TMT: {
		symbol: 'm',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 0,
	},
	TND: {
		symbol: 'د.ت.‏',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 3,
	},
	TOP: {
		symbol: 'T$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	TRY: {
		symbol: 'TL',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	TTD: {
		symbol: 'TT$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	TVD: {
		symbol: '$T',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	TWD: {
		symbol: 'NT$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	TZS: {
		symbol: 'TSh',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	UAH: {
		symbol: '₴',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	UGX: {
		symbol: 'USh',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	USD: {
		symbol: '$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	UYU: {
		symbol: '$U',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	UZS: {
		symbol: 'сўм',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	VEB: {
		symbol: 'Bs.',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	VEF: {
		symbol: 'Bs. F.',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 2,
	},
	VND: {
		symbol: '₫',
		thousands_separator: '.',
		decimal_mark: ',',
		precision: 1,
	},
	VUV: {
		symbol: 'VT',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 0,
	},
	WST: {
		symbol: 'WS$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	XAF: {
		symbol: 'F',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	XCD: {
		symbol: '$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	XOF: {
		symbol: 'F',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	XPF: {
		symbol: 'F',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	YER: {
		symbol: '﷼',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	ZAR: {
		symbol: 'R',
		thousands_separator: ' ',
		decimal_mark: ',',
		precision: 2,
	},
	ZMW: {
		symbol: 'ZK',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
	WON: {
		symbol: '₩',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	},
};

/**
 * Returns currency defaults.
 *
 * @param   {string} code      currency code
 * @returns {?object}          currency defaults
 */
export function getCurrencyDefaults( code ) {
	const defaultCurrency = {
		symbol: '$',
		thousands_separator: ',',
		decimal_mark: '.',
		precision: 2,
	};

	return currencies[ code ] || defaultCurrency;
}
