/**
 * Internal dependencies
 */

export const CONTACTS_LOADING = 'CONTACTS_LOADING';
export const CONTACTS_LOADED = 'CONTACTS_LOADED';
export const CONTACTS_FAILED = 'CONTACTS_FAILED';
export const CONTACTS_SET_SELECTED = 'CONTACTS_SET_SELECTED';
export const CONTACTS_SET_ALL_SELECTED = 'CONTACTS_SET_ALL_SELECTED';
export const CONTACTS_ITEM_SAVING = 'CONTACTS_ITEM_SAVING';
export const CONTACTS_ITEM_FAILED = 'CONTACTS_ITEM_FAILED';
export const CONTACTS_ITEM_SAVED = 'CONTACTS_ITEM_SAVED';
export const CONTACTS_ITEM_ADDED = 'CONTACTS_ITEM_ADDED';
