<?php
/**
 * List tables.
 *
 * @package  WP Ever Accounting/Admin
 * @version  1.0.2
 */
defined( 'ABSPATH' ) || exit();

if ( class_exists( 'EAccounting_Admin_List_Table', false ) ) {
	return;
}


/**
 * WC_Admin_List_Table Class.
 */
abstract class EAccounting_Admin_List_Table extends WP_List_Table {
	/**
	 * Number of results to show per page
	 *
	 * @var string
	 * @since 1.0.0
	 */
	public $per_page = 20;

	/**
	 * Main url of the page
	 *
	 * @var string
	 * @since 1.0.0
	 */
	public $base_url;

	/**
	 *
	 * Total number of discounts
	 * @var string
	 * @since 1.0.0
	 */
	public $total_count;

	/**
	 * Active number of account
	 *
	 * @var string
	 * @since 1.0.0
	 */
	public $active_count;

	/**
	 * Inactive number of account
	 *
	 * @var string
	 * @since 1.0.0
	 */
	public $inactive_count;

	/**
	 *
	 * @since 1.0.2
	 * EAccounting_Admin_List_Table constructor.
	 */
	public function __construct( $singular, $plural, $base_url ) {
		parent::__construct( array(
			'singular' => $singular,
			'plural'   => $plural,
			'ajax'     => false,
		) );
		$this->base_url = $base_url;
	}

	/**
	 * Show the search field
	 *
	 * @param string $text Label for the search box
	 * @param string $input_id ID of the search box
	 *
	 * @return void
	 * @since 1.0.0
	 *
	 */
	public function search_box( $text, $input_id ) {
		if ( empty( $_REQUEST['s'] ) && ! $this->has_items() ) {
			return;
		}

		$input_id = $input_id . '-search-input';

		if ( ! empty( $_REQUEST['orderby'] ) ) {
			echo '<input type="hidden" name="orderby" value="' . esc_attr( $_REQUEST['orderby'] ) . '" />';
		}
		if ( ! empty( $_REQUEST['order'] ) ) {
			echo '<input type="hidden" name="order" value="' . esc_attr( $_REQUEST['order'] ) . '" />';
		}
		?>
		<p class="search-box">
			<label class="screen-reader-text" for="<?php echo $input_id ?>"><?php echo $text; ?>:</label>
			<input type="search" id="<?php echo $input_id ?>" name="s" value="<?php _admin_search_query(); ?>"/>
			<?php submit_button( $text, 'button', false, false, array( 'ID' => 'search-submit' ) ); ?>
		</p>
		<?php
	}

	/**
	 * Retrieve the view types
	 *
	 * @return array $views All the views available
	 * @since 1.0.0
	 */
	public function get_views() {
		$current        = isset( $_GET['status'] ) ? sanitize_key( $_GET['status'] ) : '';
		$total_count    = '&nbsp;<span class="count">(' . $this->total_count . ')</span>';
		$active_count   = '&nbsp;<span class="count">(' . $this->active_count . ')</span>';
		$inactive_count = '&nbsp;<span class="count">(' . $this->inactive_count . ')</span>';

		$views = array(
			'all'      => sprintf( '<a href="%s"%s>%s</a>', remove_query_arg( 'status', $this->base_url ), $current === 'all' || $current == '' ? ' class="current"' : '', __( 'All', 'wp-ever-accounting' ) . $total_count ),
			'active'   => sprintf( '<a href="%s"%s>%s</a>', add_query_arg( 'status', 'active', $this->base_url ), $current === 'active' ? ' class="current"' : '', __( 'Active', 'wp-ever-accounting' ) . $active_count ),
			'inactive' => sprintf( '<a href="%s"%s>%s</a>', add_query_arg( 'status', 'inactive', $this->base_url ), $current === 'inactive' ? ' class="current"' : '', __( 'Inactive', 'wp-ever-accounting' ) . $inactive_count ),
		);

		return $views;
	}

	/**
	 * @return array|void
	 * @since 1.0.2
	 */
	public function get_columns() {
		parent::get_columns(); // TODO: Change the autogenerated stub
	}

	/**
	 * @return array
	 * @since 1.0.2
	 */
	public function get_sortable_columns() {
		return parent::get_sortable_columns(); // TODO: Change the autogenerated stub
	}

	/**
	 * @param object $item
	 * @param string $column_name
	 *
	 * @since 1.0.2
	 */
	protected function column_default( $item, $column_name ) {
		parent::column_default( $item, $column_name ); // TODO: Change the autogenerated stub
	}

	/**
	 * @param object $item
	 *
	 * @return string|void
	 * @since 1.0.2
	 */
	protected function column_cb( $item ) {
		return sprintf(
			'<input type="checkbox" name="%1$s[]" value="%2$s" />',
			$this->_args['singular'],
			$item->id
		);
	}

	/**
	 * Shows status of the item
	 *
	 * @param $item
	 *
	 * @return string
	 * @since 1.0.0
	 */
	function column_status( $item ) {
		return sprintf( '<span class="ea-item-status %1$s">%1$s</span>', $item->status );
	}

	/**
	 * Get an associative array ( option_name => option_title ) with the list
	 * of bulk actions available on this table.
	 *
	 * @return array
	 * @since 1.0.2
	 */
	protected function get_bulk_actions() {
		$actions = array(
			'activate'   => _x( 'Activate', 'List table bulk action', 'wp-ever-accounting' ),
			'deactivate' => _x( 'Deactivate', 'List table bulk action', 'wp-ever-accounting' ),
			'delete'     => _x( 'Delete', 'List table bulk action', 'wp-ever-accounting' ),
		);

		return $actions;
	}

	/**
	 * Prepares the list of items for displaying.
	 * @since 1.0.2
	 */
	public function prepare_items() {
		parent::prepare_items(); // TODO: Change the autogenerated stub
	}
}
