<?php
/**
 * Invoices Admin List Table
 *
 * @since       1.1.0
 * @subpackage  EverAccounting\Admin\ListTables
 * @package     EverAccounting
 */

use EverAccounting\Models\Invoice;

defined( 'ABSPATH' ) || exit();

if ( ! class_exists( '\EAccounting_List_Table' ) ) {
	require_once dirname( __FILE__ ) . '/class-ea-admin-list-table.php';
}

/**
 * Class EAccounting_Invoice_List_Table
 * @since 1.1.0
 */
class EAccounting_Invoice_List_Table extends EAccounting_List_Table {
	/**
	 * Default number of items to show per page
	 *
	 * @since 1.1.0
	 * @var string
	 */
	public $per_page = 20;

	/**
	 * Total number of item found
	 *
	 * @since 1.1.0
	 * @var int
	 */
	public $total_count;

	/**
	 * Number of active items found
	 *
	 * @since 1.1.0
	 * @var string
	 */
	public $active_count;

	/**
	 *  Number of inactive items found
	 *
	 * @since 1.1.0
	 * @var string
	 */
	public $inactive_count;

	/**
	 * Get things started
	 *
	 * @param array $args Optional. Arbitrary display and query arguments to pass through the list table. Default empty array.
	 *
	 * @since  1.1.0
	 *
	 * @see WP_List_Table::__construct()
	 */
	public function __construct( $args = array() ) {
		$args = (array) wp_parse_args(
			$args,
			array(
				'singular' => 'invoice',
				'plural'   => 'invoices',
			)
		);

		parent::__construct( $args );
	}

	/**
	 * Check if there is contents in the database.
	 *
	 * @return bool
	 * @since 1.1.0
	 */
	public function is_empty() {
		return parent::is_empty(); // TODO: Change the autogenerated stub
	}

	/**
	 * Render blank state.
	 *
	 * @return void
	 * @since 1.1.0
	 */
	protected function render_blank_state() {
		return parent::render_blank_state(); // TODO: Change the autogenerated stub
	}

	/**
	 * Define which columns to show on this screen.
	 *
	 * @return array
	 * @since 1.1.0
	 */
	public function define_columns() {
		return array(
			'cb'             => '<input type="checkbox" />',
			'invoice_number' => __( 'Number', 'wp-ever-accounting' ),
			'total'          => __( 'Total', 'wp-ever-accounting' ),
			'name'           => __( 'Customer Name', 'wp-ever-accounting' ),
			'issue_date'     => __( 'Invoice Date', 'wp-ever-accounting' ),
			'due_date'       => __( 'Due Date', 'wp-ever-accounting' ),
			'status'         => __( 'Status', 'wp-ever-accounting' ),
			'actions'        => __( 'Actions', 'wp-ever-accounting' ),
		);
	}

	/**
	 * Define sortable columns.
	 *
	 * @return array
	 * @since 1.1.0
	 */
	protected function define_sortable_columns() {
		return array(
			'invoice_number' => array( 'invoice_number', false ),
			'name'           => array( 'name', false ),
			'total'          => array( 'total', false ),
			'issue_date'     => array( 'issue_date', false ),
			'due_date'       => array( 'due_date', false ),
			'status'         => array( 'status', false ),
		);
	}

	/**
	 * Define bulk actions
	 *
	 * @return array
	 * @since 1.1.0
	 */
	public function define_bulk_actions() {
		return array(
			'delete' => __( 'Delete', 'wp-ever-accounting' ),
		);
	}

	/**
	 * Define primary column.
	 *
	 * @return string
	 * @since 1.1.0
	 */
	public function get_primary_column() {
		return 'invoice_number';
	}

	/**
	 * Renders the checkbox column in the accounts list table.
	 *
	 * @param Invoice $invoice The current account object.
	 *
	 * @return string Displays a checkbox.
	 * @since  1.1.0
	 *
	 */
	function column_cb( $invoice ) {
		return sprintf( '<input type="checkbox" name="invoice_id[]" value="%d"/>', $invoice->get_id() );
	}

	/**
	 * This function renders most of the columns in the list table.
	 *
	 * @param string $column_name The name of the column
	 *
	 * @param Invoice $invoice
	 *
	 * @return string The column value.
	 * @since 1.1.0
	 *
	 */
	function column_default( $invoice, $column_name ) {
		$invoice_id = $invoice->get_id();
		switch ( $column_name ) {
			case 'invoice_number':
				$invoice_number = $invoice->get_invoice_number();

				$value = sprintf(
					'<a href="%1$s">%2$s</a>',
					esc_url(
						eaccounting_admin_url(
							array(
								'action'     => 'view',
								'invoice_id' => $invoice_id,
							)
						)
					),
					$invoice_number
				);
				break;
			case 'total':
				$value = eaccounting_price( $invoice->get_total(), $invoice->get_currency_code() );
				break;
			case 'name':
				$value = $invoice->get_name();
				break;
			case 'issue_date':
				$value = eaccounting_format_datetime( $invoice->get_issue_date(), 'Y-m-d' );
				break;
			case 'due_date':
				$value = eaccounting_format_datetime( $invoice->get_due_date(), 'Y-m-d' );
				break;
			case 'status':
				$value = sprintf( '<span class="invoice-status %s">%s</span>', $invoice->get_status(), $invoice->get_status_nicename() );
				break;
			case 'actions':
				$edit_url = eaccounting_admin_url(
					array(
						'tab'        => 'invoices',
						'action'     => 'edit',
						'invoice_id' => $invoice_id,
					)
				);
				$del_url  = eaccounting_admin_url(
					array(
						'tab'        => 'invoices',
						'action'     => 'delete',
						'_wpnonce'   => wp_create_nonce( 'invoice-nonce' ),
						'invoice_id' => $invoice_id,
					)
				);
				$actions  = array(
					'edit'   => sprintf( '<a href="%s" class="dashicons dashicons-edit"></a>', esc_url( $edit_url ) ),
					'delete' => sprintf( '<a href="%s" class="dashicons dashicons-trash"></a>', esc_url( $del_url ) ),
				);
				$value    = $this->row_actions( $actions );
				break;
			default:
				return parent::column_default( $invoice, $column_name );
		}

		return apply_filters( 'eaccounting_invoice_list_table_' . $column_name, $value, $invoice );
	}

	/**
	 * Renders the message to be displayed when there are no items.
	 *
	 * @return void
	 * @since  1.1.0
	 */
	function no_items() {
		_e( 'There is no invoices found.', 'wp-ever-accounting' );
	}

	/**
	 * Process the bulk actions
	 *
	 * @return void
	 * @since 1.1.0
	 */
	public function process_bulk_action() {
		if ( empty( $_REQUEST['_wpnonce'] ) ) {
			return;
		}

		if ( ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'bulk-invoices' ) && ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'invoice-nonce' ) ) {
			return;
		}

		$ids = isset( $_GET['invoice_id'] ) ? $_GET['invoice_id'] : false;

		if ( ! is_array( $ids ) ) {
			$ids = array( $ids );
		}

		$ids = array_map( 'absint', $ids );

		if ( empty( $ids ) ) {
			return;
		}

		$action = $this->current_action();

		foreach ( $ids as $id ) {
			switch ( $action ) {
				case 'delete':
					eaccounting_delete_invoice( $id );
					break;
				default:
					do_action( 'eaccounting_invoices_do_bulk_action_' . $this->current_action(), $id );
			}
		}

		if ( isset( $_GET['_wpnonce'] ) ) {
			wp_safe_redirect(
				remove_query_arg(
					array(
						'invoice_id',
						'action',
						'_wpnonce',
						'_wp_http_referer',
						'action2',
						'paged',
					)
				)
			);
			exit();
		}
	}

	/**
	 * Retrieve all the data for the table.
	 * Setup the final data for the table
	 *
	 * @return void
	 * @since 1.1.0
	 */
	public function prepare_items() {
		$columns               = $this->get_columns();
		$hidden                = array();
		$sortable              = $this->get_sortable_columns();
		$this->_column_headers = array( $columns, $hidden, $sortable );

		$this->process_bulk_action();

		$page    = isset( $_GET['paged'] ) ? absint( $_GET['paged'] ) : 1;
		$status  = isset( $_GET['status'] ) ? $_GET['status'] : '';
		$search  = isset( $_GET['s'] ) ? $_GET['s'] : '';
		$order   = isset( $_GET['order'] ) ? $_GET['order'] : 'DESC';
		$orderby = isset( $_GET['orderby'] ) ? $_GET['orderby'] : 'id';

		$per_page = $this->per_page;

		$args = wp_parse_args(
			$this->query_args,
			array(
				'number'   => $per_page,
				'offset'   => $per_page * ( $page - 1 ),
				'per_page' => $per_page,
				'page'     => $page,
				'status'   => $status,
				'search'   => $search,
				'orderby'  => eaccounting_clean( $orderby ),
				'order'    => eaccounting_clean( $order ),
			)
		);

		$args              = apply_filters( 'eaccounting_invoice_table_query_args', $args, $this );
		$this->items       = eaccounting_get_invoices( $args );
		$this->total_count = eaccounting_get_invoices( array_merge( $args, array( 'count_total' => true ) ) );
		$this->set_pagination_args(
			array(
				'total_items' => $this->total_count,
				'per_page'    => $per_page,
				'total_pages' => ceil( $this->total_count / $per_page ),
			)
		);
	}
}
