<?php
/**
 * Customers list table
 *
 * Admin customers list table.
 *
 * @since       1.0.2
 * @subpackage  EverAccounting\Admin\ListTables
 * @package     EverAccounting
 */

namespace EverAccounting\Admin\ListTables;

use EverAccounting\Abstracts\List_Table;
use EverAccounting\Models\Customer;

/**
 * Class List_Table_Customers
 *
 * @since   1.0.2
 * @package EverAccounting\Admin\Sales
 */
class List_Table_Customers extends List_Table {
	/**
	 * Type of the table should be use plural name.
	 *
	 * This will be used for filtering methods.
	 *
	 * @since 1.0.2
	 * @var string
	 */
	protected $list_table_type = 'customers';

	/**
	 * Default number of items to show per page
	 *
	 * @since 1.0.2
	 * @var string
	 */
	public $per_page = 20;

	/**
	 * Total number of item found
	 *
	 * @since 1.0.2
	 * @var int
	 */
	public $total_count;

	/**
	 * Number of active items found
	 *
	 * @since 1.0.2
	 * @var string
	 */
	public $active_count;

	/**
	 *  Number of inactive items found
	 *
	 * @since 1.0.2
	 * @var string
	 */
	public $inactive_count;

	/**
	 * Get things started
	 *
	 * @since  1.0.2
	 *
	 * @see    WP_List_Table::__construct()
	 *
	 * @param array $args Optional. Arbitrary display and query arguments to pass through the list table. Default empty array.
	 */
	public function __construct( $args = array() ) {
		$args = (array) wp_parse_args(
			$args,
			array(
				'singular' => 'customer',
				'plural'   => 'customers',
			)
		);

		parent::__construct( $args );
	}

	/**
	 * Check if there is contents in the database.
	 *
	 * @since 1.0.2
	 * @return bool
	 */
	public function is_empty() {
		return parent::is_empty(); // TODO: Change the autogenerated stub
	}

	/**
	 * Render blank state.
	 *
	 * @since 1.0.2
	 * @return void
	 */
	protected function render_blank_state() {
		return parent::render_blank_state(); // TODO: Change the autogenerated stub
	}

	/**
	 * Define which columns to show on this screen.
	 *
	 * @since 1.0.2
	 * @return array
	 */
	public function define_columns() {
		return array(
			'cb'      => '<input type="checkbox" />',
			'name'    => __( 'Name', 'wp-ever-accounting' ),
			'email'   => __( 'Email', 'wp-ever-accounting' ),
			'phone'   => __( 'Phone', 'wp-ever-accounting' ),
			// 'sales'   => __( 'Sales', 'wp-ever-accounting' ),
			'enabled' => __( 'Enabled', 'wp-ever-accounting' ),
			'actions' => __( 'Actions', 'wp-ever-accounting' ),
		);
	}

	/**
	 * Define sortable columns.
	 *
	 * @since 1.0.2
	 * @return array
	 */
	protected function define_sortable_columns() {
		return array(
			'name'    => array( 'name', false ),
			'email'   => array( 'email', false ),
			'phone'   => array( 'phone', false ),
			'sales'   => array( 'sales', false ),
			'enabled' => array( 'enabled', false ),
		);
	}

	/**
	 * Define bulk actions
	 *
	 * @since 1.0.2
	 * @return array
	 */
	public function define_bulk_actions() {
		return array(
			'enable'  => __( 'Enable', 'wp-ever-accounting' ),
			'disable' => __( 'Disable', 'wp-ever-accounting' ),
			'delete'  => __( 'Delete', 'wp-ever-accounting' ),
		);
	}

	/**
	 * Define primary column.
	 *
	 * @since 1.0.2
	 * @return string
	 */
	public function get_primary_column() {
		return 'date';
	}


	/**
	 * Renders the checkbox column in the customers list table.
	 *
	 * @since  1.0.2
	 *
	 * @param Customer $customer The current object.
	 *
	 * @return string Displays a checkbox.
	 */
	function column_cb( $customer ) {
		return sprintf( '<input type="checkbox" name="customer_id[]" value="%d"/>', $customer->get_id() );
	}

	/**
	 * This function renders most of the columns in the list table.
	 *
	 * @since 1.0.2
	 *
	 * @param string   $column_name The name of the column
	 *
	 * @param Customer $customer
	 *
	 * @return string The column value.
	 */
	function column_default( $customer, $column_name ) {
		$customer_id = $customer->get_id();
		switch ( $column_name ) {
			case 'name':
				$url   = eaccounting_admin_url(
					array(
						'tab'         => 'customers',
						'action'      => 'view',
						'customer_id' => $customer_id,
					)
				);
				$value = sprintf( '<a href="%1$s">%2$s</a>', esc_url( $url ), esc_html( $customer->get_name() ) );
				break;
			case 'enabled':
				$nonce   = wp_create_nonce( 'ea_manage_customer' );
				$enabled = $customer->get_enabled();
				$value   = '<label class="ea-toggle">';
				$value  .= sprintf( '<input type="checkbox" name="enabled" value="1" data-id="%d" data-nonce="%s" checked="%s">', $customer_id, $nonce, checked( 1, $enabled, false ) );
				$value  .= sprintf( '<span data-label-off="%s" data-label-on="%s" class="ea-toggle-slider"></span>', __( 'No', 'wp-ever-accounting' ), __( 'Yes', 'wp-ever-accounting' ) );
				$value  .= '</label>';
				break;
			case 'actions':
				$edit_url = eaccounting_admin_url(
					array(
						'tab'         => 'customers',
						'action'      => 'edit',
						'customer_id' => $customer_id,
					)
				);
				$del_url  = eaccounting_admin_url(
					array(
						'tab'         => 'customers',
						'action'      => 'delete',
						'customer_id' => $customer_id,
					)
				);
				$actions  = array(
					'edit'   => sprintf( '<a href="%s" class="dashicons dashicons-edit"></a>', esc_url( $edit_url ) ),
					'delete' => sprintf( '<a href="%s" class="dashicons dashicons-trash"></a>', esc_url( $del_url ) ),
				);
				$value    = $this->row_actions( $actions );
				break;
			default:
				return parent::column_default( $customer, $column_name );
		}

		return apply_filters( 'eaccounting_' . $this->list_table_type . '_table_' . $column_name, $value, $customer );
	}

	/**
	 * Renders the message to be displayed when there are no items.
	 *
	 * @since  1.0.2
	 * @return void
	 */
	function no_items() {
		_e( 'No customers found.', 'wp-ever-accounting' );
	}

	/**
	 * Process the bulk actions
	 *
	 * @since 1.0.2
	 * @return void
	 */
	public function process_bulk_action() {
		if ( empty( $_REQUEST['_wpnonce'] ) ) {
			return;
		}

		if ( ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'bulk-customers' ) && ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'customer-nonce' ) ) {
			return;
		}

		$ids = isset( $_GET['customer_id'] ) ? $_GET['customer_id'] : false;

		if ( ! is_array( $ids ) ) {
			$ids = array( $ids );
		}

		$ids = array_map( 'absint', $ids );

		if ( empty( $ids ) ) {
			return;
		}

		$action = $this->current_action();
		foreach ( $ids as $id ) {
			switch ( $action ) {
				case 'enable':
					eaccounting_insert_customer(
						array(
							'id'      => $id,
							'enabled' => '1',
						)
					);
					break;
				case 'disable':
					eaccounting_insert_customer(
						array(
							'id'      => $id,
							'enabled' => '0',
						)
					);
					break;
				case 'delete':
					eaccounting_insert_customer( $id );
					break;
				default:
					do_action( 'eaccounting_customers_do_bulk_action_' . $this->current_action(), $id );
			}
		}

		if ( isset( $_GET['_wpnonce'] ) ) {
			wp_safe_redirect(
				remove_query_arg(
					array(
						'customer_id',
						'action',
						'_wpnonce',
						'_wp_http_referer',
						'action2',
						'paged',
					)
				)
			);
			exit();
		}
	}

	/**
	 * Retrieve all the data for the table.
	 * Setup the final data for the table
	 *
	 * @since 1.0.2
	 * @return void
	 */
	public function prepare_items() {
		$columns               = $this->get_columns();
		$hidden                = $this->get_hidden_columns();
		$sortable              = $this->get_sortable_columns();
		$this->_column_headers = array( $columns, $hidden, $sortable );

		$this->process_bulk_action();

		$page    = isset( $_GET['paged'] ) ? absint( $_GET['paged'] ) : 1;
		$status  = isset( $_GET['status'] ) ? $_GET['status'] : '';
		$search  = isset( $_GET['s'] ) ? $_GET['s'] : '';
		$order   = isset( $_GET['order'] ) ? $_GET['order'] : 'DESC';
		$orderby = isset( $_GET['orderby'] ) ? $_GET['orderby'] : 'id';

		$per_page = $this->get_per_page();

		$args = wp_parse_args(
			$this->query_args,
			array(
				'number'   => $per_page,
				'offset'   => $per_page * ( $page - 1 ),
				'per_page' => $per_page,
				'page'     => $page,
				'search'   => $search,
				'status'   => $status,
				'orderby'  => eaccounting_clean( $orderby ),
				'order'    => eaccounting_clean( $order ),
				'type'     => 'customer',
			)
		);

		$args = apply_filters( 'eaccounting_customers_table_get_customers', $args, $this );

		$this->items       = eaccounting_get_customers( $args );
		$this->total_count = eaccounting_get_customers( array_merge( $args, array( 'count_total' => true ) ) );

		$total_items = $this->total_count;

		$status = isset( $_GET['status'] ) ? $_GET['status'] : 'any';

		switch ( $status ) {
			case 'active':
				$total_items = $this->active_count;
				break;
			case 'inactive':
				$total_items = $this->inactive_count;
				break;
			case 'any':
				$total_items = $this->total_count;
				break;
		}

		$this->set_pagination_args(
			array(
				'total_items' => $total_items,
				'per_page'    => $per_page,
				'total_pages' => ceil( $total_items / $per_page ),
			)
		);
	}
}
