<?php
/**
 * Vendors list table
 *
 * Admin vendors list table.
 *
 *
 * @since       1.0.2
 * @subpackage  EverAccounting\Admin\ListTables
 * @package     EverAccounting
 */

namespace EverAccounting\Admin\ListTables;

use EverAccounting\Abstracts\List_Table;
use EverAccounting\Contact;
use EverAccounting\Query_Contact;

/**
 * Class List_Table_Vendors
 *
 * @since   1.0.2
 * @package EverAccounting\Admin\ListTables
 */
class List_Table_Vendors extends List_Table {
	/**
	 * Type of the table should be use plural name.
	 *
	 * This will be used for filtering methods.
	 *
	 * @since 1.0.2
	 * @var string
	 */
	protected $list_table_type = 'vendors';

	/**
	 * Default number of items to show per page
	 *
	 * @since 1.0.2
	 * @var string
	 */
	public $per_page = 20;

	/**
	 * Total number of item found
	 *
	 * @since 1.0.2
	 * @var int
	 */
	public $total_count;

	/**
	 * Number of active items found
	 *
	 * @since 1.0
	 * @var string
	 */
	public $active_count;

	/**
	 *  Number of inactive items found
	 *
	 * @since 1.0
	 * @var string
	 */
	public $inactive_count;

	/**
	 * Get things started
	 *
	 * @since  1.0.2
	 *
	 * @see    WP_List_Table::__construct()
	 *
	 * @param array $args Optional. Arbitrary display and query arguments to pass through the list table. Default empty array.
	 *
	 */
	public function __construct( $args = array() ) {
		$args = (array) wp_parse_args( $args, array(
			'singular' => 'vendor',
			'plural'   => 'vendors',
		) );

		parent::__construct( $args );
	}

	/**
	 * Check if there is contents in the database.
	 *
	 * @since 1.0.2
	 * @return bool
	 */
	public function is_empty() {
		return parent::is_empty(); // TODO: Change the autogenerated stub
	}

	/**
	 * Render blank state.
	 *
	 * @since 1.0.2
	 * @return void
	 */
	protected function render_blank_state() {
		return parent::render_blank_state(); // TODO: Change the autogenerated stub
	}

	/**
	 * Define which columns to show on this screen.
	 *
	 * @since 1.0.2
	 * @return array
	 */
	public function define_columns() {
		return array(
			'cb'      => '<input type="checkbox" />',
			'name'    => __( 'Name', 'wp-ever-accounting' ),
			'email'   => __( 'Email', 'wp-ever-accounting' ),
			'phone'   => __( 'Phone', 'wp-ever-accounting' ),
			//'sales'   => __( 'Sales', 'wp-ever-accounting' ),
			'enabled' => __( 'Enabled', 'wp-ever-accounting' ),
			'actions' => __( 'Actions', 'wp-ever-accounting' ),
		);
	}

	/**
	 * Define sortable columns.
	 *
	 * @since 1.0.2
	 * @return array
	 */
	protected function define_sortable_columns() {
		return array(
			'name'    => array( 'name', false ),
			'email'   => array( 'email', false ),
			'phone'   => array( 'phone', false ),
			'sales'   => array( 'sales', false ),
			'enabled' => array( 'enabled', false ),
		);
	}

	/**
	 * Define bulk actions
	 *
	 * @since 1.0.2
	 * @return array
	 */
	public function define_bulk_actions() {
		return array(
			'enable'  => __( 'Enable', 'wp-ever-accounting' ),
			'disable' => __( 'Disable', 'wp-ever-accounting' ),
			'delete'  => __( 'Delete', 'wp-ever-accounting' ),
		);
	}

	/**
	 * Define primary column.
	 *
	 * @since 1.0.2
	 * @return string
	 */
	public function get_primary_column() {
		return 'date';
	}


	/**
	 * Renders the checkbox column in the vendors list table.
	 *
	 *
	 * @since  1.0.2
	 *
	 * @param Contact $vendor The current object.
	 *
	 * @return string Displays a checkbox.
	 */
	function column_cb( $vendor ) {
		return sprintf( '<input type="checkbox" name="vendor_id[]" value="%d"/>', $vendor->get_id() );
	}

	/**
	 * Renders the "Name" column in the vendor list table.
	 *
	 *
	 * @since  1.0.2
	 *
	 * @param Contact $vendor The current contact object.
	 *
	 * @return string Data shown in the Name column.
	 */
	function column_name( $vendor ) {
		$name = $vendor->get_name();

		$value = sprintf( '<a href="%1$s">%2$s</a>',
			esc_url( eaccounting_admin_url( [ 'action' => 'edit', 'tab' => 'vendors', 'vendor_id' => $vendor->get_id() ] ) ),
			$name
		);

		return apply_filters( 'eaccounting_vendors_table_name', $value, $vendor );
	}

	/**
	 * Renders the "Email" column in the vendor list table.
	 *
	 *
	 * @since  1.0.2
	 *
	 * @param Contact $vendor The current contact object.
	 *
	 * @return string Data shown in the Email column.
	 */
	function column_email( $vendor ) {
		$email = empty( $vendor->get_email() ) ? '&mdash;' : $vendor->get_email();

		return apply_filters( 'eaccounting_vendors_table_email', $email, $vendor );
	}

	/**
	 * Renders the "Phone" column in the vendor list table.
	 *
	 *
	 * @since  1.0.2
	 *
	 * @param Contact $vendor The current contact object.
	 *
	 * @return string Data shown in the Phone column.
	 */
	function column_phone( $vendor ) {
		$phone = empty( $vendor->get_phone() ) ? '&mdash;' : $vendor->get_phone();

		return apply_filters( 'eaccounting_vendors_table_phone', $phone, $vendor );
	}

	/**
	 * Renders the "enabled" column in the list table.
	 *
	 * @since  1.0.2
	 *
	 * @param Contact $vendor The current object.
	 *
	 * @return string Data shown in the "enabled" column.
	 */
	function column_enabled( $vendor ) {
		ob_start();
		eaccounting_toggle( array(
			'name'  => 'enabled',
			'id'    => 'enabled_' . $vendor->get_id(),
			'value' => $vendor->get_enabled( 'edit' ),
			'naked' => true,
			'class' => 'ea_item_status_update',
			'attr'  => array(
				'data-object_id'   => $vendor->get_id(),
				'data-nonce'       => wp_create_nonce( 'ea_status_update' ),
				'data-object_type' => 'vendor'
			)
		) );
		$output = ob_get_contents();
		ob_get_clean();

		return apply_filters( 'eaccounting_vendors_table_enabled', $output, $vendor );
	}

	/**
	 * @since 1.0.2
	 *
	 * @param $vendor
	 *
	 * @return string
	 */
	function column_actions( $vendor ) {
		$base_uri    = eaccounting_admin_url( array( 'contact_id' => $vendor->get_id(), 'tab' => 'vendors' ) );
		$row_actions = array();

		$row_actions['edit']   = array(
			'label' => __( 'Edit', 'wp-ever-accounting' ),
			array( 'action' => 'edit' ),
			array( 'base_uri' => $base_uri )
		);
		$row_actions['delete'] = array(
			'label' => __( 'Delete', 'wp-ever-accounting' ),
			array( 'base_uri' => $base_uri, 'nonce' => 'account-nonce' )
		);

		$row_actions = apply_filters( 'eaccounting_vendors_table_row_actions', $row_actions, $vendor );

		return $this->row_actions( $row_actions );
	}


	/**
	 * Renders the message to be displayed when there are no items.
	 *
	 * @since  1.0.2
	 * @return void
	 */
	function no_items() {
		_e( 'No vendors found.', 'wp-ever-accounting' );
	}

	/**
	 * Process the bulk actions
	 *
	 * @since 1.0.2
	 * @return void
	 */
	public function process_bulk_action() {
		if ( empty( $_REQUEST['_wpnonce'] ) ) {
			return;
		}

		if ( ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'bulk-vendors' ) && ! wp_verify_nonce( $_REQUEST['_wpnonce'], 'vendor-nonce' ) ) {
			return;
		}

		$ids = isset( $_GET['vendor_id'] ) ? $_GET['vendor_id'] : false;

		if ( ! is_array( $ids ) ) {
			$ids = array( $ids );
		}

		$ids = array_map( 'absint', $ids );

		if ( empty( $ids ) ) {
			return;
		}

		$action = $this->current_action();
		foreach ( $ids as $id ) {
			switch ( $action ) {
				case 'enable':
					eaccounting_insert_contact( array(
						'id'      => $id,
						'enabled' => '1'
					) );
					break;
				case 'disable':
					eaccounting_insert_contact( array(
						'id'      => $id,
						'enabled' => '0'
					) );
					break;
				case 'delete':
					eaccounting_delete_contact( $id );
					break;
				default:
					do_action( 'eaccounting_vendors_do_bulk_action_' . $this->current_action(), $id );
			}
		}

		if ( ! empty( $action ) ) {
			wp_safe_redirect( remove_query_arg( [
				'vendor_id',
				'action',
				'_wpnonce',
				'_wp_http_referer',
				'action2',
				'doaction',
				'paged'
			] ) );
			exit();
		}
	}

	/**
	 * Retrieve all the data for the table.
	 * Setup the final data for the table
	 *
	 * @since 1.0.2
	 * @return void
	 */
	public function prepare_items() {
		$columns               = $this->get_columns();
		$hidden                = $this->get_hidden_columns();
		$sortable              = $this->get_sortable_columns();
		$this->_column_headers = array( $columns, $hidden, $sortable );

		$this->process_bulk_action();

		$page    = isset( $_GET['paged'] ) ? absint( $_GET['paged'] ) : 1;
		$status  = isset( $_GET['status'] ) ? $_GET['status'] : '';
		$search  = isset( $_GET['s'] ) ? $_GET['s'] : '';
		$order   = isset( $_GET['order'] ) ? $_GET['order'] : 'DESC';
		$orderby = isset( $_GET['orderby'] ) ? $_GET['orderby'] : 'id';

		$per_page = $this->get_per_page();

		$args = wp_parse_args( $this->query_args, array(
			'number'  => $per_page,
			'offset'  => $per_page * ( $page - 1 ),
			'search'  => $search,
			'status'  => $status,
			'orderby' => eaccounting_clean( $orderby ),
			'order'   => eaccounting_clean( $order ),
			'type'    => 'vendor'
		) );

		$args = apply_filters( 'eaccounting_vendors_table_get_vendors', $args, $this );

		$this->items = Query_Contact::init()->where( $args )->get( OBJECT, 'eaccounting_get_contact' );

		$this->total_count = Query_Contact::init()->where( $args )->count();

		$this->active_count = Query_Contact::init()->where( array_merge( $this->query_args, array(
			'status' => 'active',
			'search' => $search
		) ) )->count();

		$this->inactive_count = Query_Contact::init()->where( array_merge( $this->query_args, array(
			'status' => 'inactive',
			'search' => $search
		) ) )->count();

		$total_items = $this->total_count;

		$status = isset( $_GET['status'] ) ? $_GET['status'] : 'any';

		switch ( $status ) {
			case 'active':
				$total_items = $this->active_count;
				break;
			case 'inactive':
				$total_items = $this->inactive_count;
				break;
			case 'any':
				$total_items = $this->total_count;
				break;
		}

		$this->set_pagination_args( array(
			'total_items' => $total_items,
			'per_page'    => $per_page,
			'total_pages' => ceil( $total_items / $per_page )
		) );
	}
}
