<?php
/**
 * Payment repository.
 *
 * Handle payment insert, update, delete & retrieve from database.
 *
 * @version   1.1.0
 * @package   EverAccounting\Repositories
 */

namespace EverAccounting\Repositories;

use EverAccounting\Abstracts\TransactionsRepository;
use EverAccounting\Models\Income;

defined( 'ABSPATH' ) || exit;

/**
 * Class Payments
 *
 * @since   1.1.0
 *
 * @package EverAccounting\Repositories
 */
class Expenses extends TransactionsRepository {

	/**
	 * Accounts constructor.
	 */
	public function __construct() {
		parent::__construct();
		$this->object_type = 'expense';
	}

	/**
	 * @param array $args
	 * @since 1.0.
	 *
	 * @return array|int
	 */
	public function get_items( $args = array(), $callback = false ) {
		$args            = wp_parse_args( $args, array( 'where' => array() ) );
		$args['where'][] = array(
			'joint'     => 'AND',
			'condition' => "{$this->table_name}.type = 'expense' ",
		);

		return parent::get_items( $args, $callback ); // TODO: Change the autogenerated stub
	}

	/**
	 * Retrieves column defaults.
	 *
	 * Sub-classes can define default for any/all of columns defined in the get_columns() method.
	 *
	 * @since 1.1.0
	 * @return array All defined column defaults.
	 */
	public static function get_defaults() {
		return array_merge( parent::get_defaults(), array( 'type' => 'expense' ) );
	}
}
