/**
 * Internal dependencies
 */

export const RECONCILIATIONS_LOADING = 'RECONCILIATIONS_LOADING';
export const RECONCILIATIONS_LOADED = 'RECONCILIATIONS_LOADED';
export const RECONCILIATIONS_FAILED = 'RECONCILIATIONS_FAILED';
export const RECONCILIATIONS_SET_SELECTED = 'RECONCILIATIONS_SET_SELECTED';
export const RECONCILIATIONS_SET_ALL_SELECTED = 'RECONCILIATIONS_SET_ALL_SELECTED';
export const RECONCILIATIONS_ITEM_SAVING = 'RECONCILIATIONS_ITEM_SAVING';
export const RECONCILIATIONS_ITEM_FAILED = 'RECONCILIATIONS_ITEM_FAILED';
export const RECONCILIATIONS_ITEM_SAVED = 'RECONCILIATIONS_ITEM_SAVED';
export const RECONCILIATIONS_ITEM_ADDED = 'RECONCILIATIONS_ITEM_ADDED';
