/**
 * Internal dependencies
 */

export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const TRANSACTIONS_LOADED = 'TRANSACTIONS_LOADED';
export const TRANSACTIONS_FAILED = 'TRANSACTIONS_FAILED';
export const TRANSACTIONS_SET_SELECTED = 'TRANSACTIONS_SET_SELECTED';
export const TRANSACTIONS_SET_ALL_SELECTED = 'TRANSACTIONS_SET_ALL_SELECTED';
export const TRANSACTIONS_ITEM_SAVING = 'TRANSACTIONS_ITEM_SAVING';
export const TRANSACTIONS_ITEM_FAILED = 'TRANSACTIONS_ITEM_FAILED';
export const TRANSACTIONS_ITEM_SAVED = 'TRANSACTIONS_ITEM_SAVED';
export const TRANSACTIONS_DISPLAY_SET = 'TRANSACTIONS_DISPLAY_SET';
