import Base from './base.js';

export default Base.extend( {
	endpoint: 'documents',

	defaults: {
		id: '',
		type: '',
		status: '',
		number: '',
		contact_id: '',
		items_total: '',
		discount_total: '',
		shipping_total: '',
		fees_total: '',
		tax_total: '',
		total: '',
		total_paid: '',
		balance: '',
		discount_amount: '',
		discount_type: '',
		billing_data: '',
		reference: '',
		note: '',
		tax_inclusive: '',
		vat_exempt: '',
		issue_date: '',
		due_date: '',
		sent_date: '',
		payment_date: '',
		currency_code: '',
		exchange_rate: '',
		parent_id: '',
		created_via: '',
		creator_id: '',
		uuid: '',
		updated_at: '',
		created_at: '',
	},
} );
