<?php
/**
 * EverAccounting miscellaneous functions.
 *
 * Functions for extra support of the plugin.
 *
 * @package EverAccounting
 * @since   1.0.2
 */

defined( 'ABSPATH' ) || exit;

/**
 * Generate a random color
 *
 * since 1.0.2
 *
 * @return string hex color code.
 */
function eaccounting_get_random_color() {
	return '#' . str_pad( dechex( random_int( 0, 0xFFFFFF ) ), 6, '0', STR_PAD_LEFT );
}


/**
 * Get global currencies
 *
 * @return mixed|void
 * @since 1.0.2
 */
function eaccounting_get_currency_codes() {
	$currencies = array(
		'AED' => array(
			'name'               => 'UAE Dirham',
			'code'               => 'AED',
			'number'             => 784,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'د.إ',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'AFN' => array(
			'name'               => 'Afghani',
			'code'               => 'AFN',
			'number'             => 971,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '؋',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ALL' => array(
			'name'               => 'Lek',
			'code'               => 'ALL',
			'number'             => 8,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'L',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'AMD' => array(
			'name'               => 'Armenian Dram',
			'code'               => 'AMD',
			'number'             => 51,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'դր.',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ANG' => array(
			'name'               => 'Netherlands Antillean Guilder',
			'code'               => 'ANG',
			'number'             => 532,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ƒ',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'AOA' => array(
			'name'               => 'Kwanza',
			'code'               => 'AOA',
			'number'             => 973,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Kz',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ARS' => array(
			'name'               => 'Argentine Peso',
			'code'               => 'ARS',
			'number'             => 32,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'AUD' => array(
			'name'               => 'Australian Dollar',
			'code'               => 'AUD',
			'number'             => 36,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ' ',
		),

		'AWG' => array(
			'name'               => 'Aruban Florin',
			'code'               => 'AWG',
			'number'             => 533,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ƒ',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'AZN' => array(
			'name'               => 'Azerbaijanian Manat',
			'code'               => 'AZN',
			'number'             => 944,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₼',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BAM' => array(
			'name'               => 'Convertible Mark',
			'code'               => 'BAM',
			'number'             => 977,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'КМ',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BBD' => array(
			'name'               => 'Barbados Dollar',
			'code'               => 'BBD',
			'number'             => 52,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BDT' => array(
			'name'               => 'Taka',
			'code'               => 'BDT',
			'number'             => 50,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '৳',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BGN' => array(
			'name'               => 'Bulgarian Lev',
			'code'               => 'BGN',
			'number'             => 975,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'лв',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BHD' => array(
			'name'               => 'Bahraini Dinar',
			'code'               => 'BHD',
			'number'             => 48,
			'precision'          => 3,
			'subunit'            => 1000,
			'symbol'             => 'ب.د',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BIF' => array(
			'name'               => 'Burundi Franc',
			'code'               => 'BIF',
			'number'             => 108,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Fr',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BMD' => array(
			'name'               => 'Bermudian Dollar',
			'code'               => 'BMD',
			'number'             => 60,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BND' => array(
			'name'               => 'Brunei Dollar',
			'code'               => 'BND',
			'number'             => 96,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BOB' => array(
			'name'               => 'Boliviano',
			'code'               => 'BOB',
			'number'             => 68,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Bs.',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BOV' => array(
			'name'               => 'Mvdol',
			'code'               => 'BOV',
			'number'             => 984,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Bs.',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BRL' => array(
			'name'               => 'Brazilian Real',
			'code'               => 'BRL',
			'number'             => 986,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'R$',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'BSD' => array(
			'name'               => 'Bahamian Dollar',
			'code'               => 'BSD',
			'number'             => 44,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BTN' => array(
			'name'               => 'Ngultrum',
			'code'               => 'BTN',
			'number'             => 64,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Nu.',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BWP' => array(
			'name'               => 'Pula',
			'code'               => 'BWP',
			'number'             => 72,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'P',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'BYN' => array(
			'name'               => 'Belarussian Ruble',
			'code'               => 'BYN',
			'number'             => 974,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Br',
			'position'           => 'after',
			'decimal_separator'  => ',',
			'thousand_separator' => ' ',
		),

		'BZD' => array(
			'name'               => 'Belize Dollar',
			'code'               => 'BZD',
			'number'             => 84,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'CAD' => array(
			'name'               => 'Canadian Dollar',
			'code'               => 'CAD',
			'number'             => 124,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'CDF' => array(
			'name'               => 'Congolese Franc',
			'code'               => 'CDF',
			'number'             => 976,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Fr',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'CHF' => array(
			'name'               => 'Swiss Franc',
			'code'               => 'CHF',
			'number'             => 756,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'CHF',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'CLF' => array(
			'name'               => 'Unidades de fomento',
			'code'               => 'CLF',
			'number'             => 990,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'UF',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'CLP' => array(
			'name'               => 'Chilean Peso',
			'code'               => 'CLP',
			'number'             => 152,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'CNY' => array(
			'name'               => 'Yuan Renminbi',
			'code'               => 'CNY',
			'number'             => 156,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '¥',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'COP' => array(
			'name'               => 'Colombian Peso',
			'code'               => 'COP',
			'number'             => 170,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'CRC' => array(
			'name'               => 'Costa Rican Colon',
			'code'               => 'CRC',
			'number'             => 188,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₡',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'CUC' => array(
			'name'               => 'Peso Convertible',
			'code'               => 'CUC',
			'number'             => 931,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'CUP' => array(
			'name'               => 'Cuban Peso',
			'code'               => 'CUP',
			'number'             => 192,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'CVE' => array(
			'name'               => 'Cape Verde Escudo',
			'code'               => 'CVE',
			'number'             => 132,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'CZK' => array(
			'name'               => 'Czech Koruna',
			'code'               => 'CZK',
			'number'             => 203,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Kč',
			'position'           => 'after',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'DJF' => array(
			'name'               => 'Djibouti Franc',
			'code'               => 'DJF',
			'number'             => 262,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Fdj',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'DKK' => array(
			'name'               => 'Danish Krone',
			'code'               => 'DKK',
			'number'             => 208,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'kr',
			'position'           => 'after',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'DOP' => array(
			'name'               => 'Dominican Peso',
			'code'               => 'DOP',
			'number'             => 214,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'DZD' => array(
			'name'               => 'Algerian Dinar',
			'code'               => 'DZD',
			'number'             => 12,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'د.ج',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'EGP' => array(
			'name'               => 'Egyptian Pound',
			'code'               => 'EGP',
			'number'             => 818,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ج.م',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ERN' => array(
			'name'               => 'Nakfa',
			'code'               => 'ERN',
			'number'             => 232,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Nfk',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ETB' => array(
			'name'               => 'Ethiopian Birr',
			'code'               => 'ETB',
			'number'             => 230,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Br',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'EUR' => array(
			'name'               => 'Euro',
			'code'               => 'EUR',
			'number'             => 978,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '€',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'FJD' => array(
			'name'               => 'Fiji Dollar',
			'code'               => 'FJD',
			'number'             => 242,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'FKP' => array(
			'name'               => 'Falkland Islands Pound',
			'code'               => 'FKP',
			'number'             => 238,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '£',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'GBP' => array(
			'name'               => 'Pound Sterling',
			'code'               => 'GBP',
			'number'             => 826,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '£',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'GEL' => array(
			'name'               => 'Lari',
			'code'               => 'GEL',
			'number'             => 981,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ლ',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'GHS' => array(
			'name'               => 'Ghana Cedi',
			'code'               => 'GHS',
			'number'             => 936,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₵',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'GIP' => array(
			'name'               => 'Gibraltar Pound',
			'code'               => 'GIP',
			'number'             => 292,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '£',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'GMD' => array(
			'name'               => 'Dalasi',
			'code'               => 'GMD',
			'number'             => 270,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'D',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'GNF' => array(
			'name'               => 'Guinea Franc',
			'code'               => 'GNF',
			'number'             => 324,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Fr',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'GTQ' => array(
			'name'               => 'Quetzal',
			'code'               => 'GTQ',
			'number'             => 320,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Q',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'GYD' => array(
			'name'               => 'Guyana Dollar',
			'code'               => 'GYD',
			'number'             => 328,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'HKD' => array(
			'name'               => 'Hong Kong Dollar',
			'code'               => 'HKD',
			'number'             => 344,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'HNL' => array(
			'name'               => 'Lempira',
			'code'               => 'HNL',
			'number'             => 340,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'L',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'HRK' => array(
			'name'               => 'Croatian Kuna',
			'code'               => 'HRK',
			'number'             => 191,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'kn',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'HTG' => array(
			'name'               => 'Gourde',
			'code'               => 'HTG',
			'number'             => 332,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'G',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'HUF' => array(
			'name'               => 'Forint',
			'code'               => 'HUF',
			'number'             => 348,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Ft',
			'position'           => 'after',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'IDR' => array(
			'name'               => 'Rupiah',
			'code'               => 'IDR',
			'number'             => 360,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Rp',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'ILS' => array(
			'name'               => 'New Israeli Sheqel',
			'code'               => 'ILS',
			'number'             => 376,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₪',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'INR' => array(
			'name'               => 'Indian Rupee',
			'code'               => 'INR',
			'number'             => 356,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₹',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'IQD' => array(
			'name'               => 'Iraqi Dinar',
			'code'               => 'IQD',
			'number'             => 368,
			'precision'          => 3,
			'subunit'            => 1000,
			'symbol'             => 'ع.د',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'IRR' => array(
			'name'               => 'Iranian Rial',
			'code'               => 'IRR',
			'number'             => 364,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '﷼',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ISK' => array(
			'name'               => 'Iceland Krona',
			'code'               => 'ISK',
			'number'             => 352,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'kr',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'JMD' => array(
			'name'               => 'Jamaican Dollar',
			'code'               => 'JMD',
			'number'             => 388,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'JOD' => array(
			'name'               => 'Jordanian Dinar',
			'code'               => 'JOD',
			'number'             => 400,
			'precision'          => 3,
			'subunit'            => 100,
			'symbol'             => 'د.ا',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'JPY' => array(
			'name'               => 'Yen',
			'code'               => 'JPY',
			'number'             => 392,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => '¥',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KES' => array(
			'name'               => 'Kenyan Shilling',
			'code'               => 'KES',
			'number'             => 404,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'KSh',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KGS' => array(
			'name'               => 'Som',
			'code'               => 'KGS',
			'number'             => 417,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'som',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KHR' => array(
			'name'               => 'Riel',
			'code'               => 'KHR',
			'number'             => 116,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '៛',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KMF' => array(
			'name'               => 'Comoro Franc',
			'code'               => 'KMF',
			'number'             => 174,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Fr',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KPW' => array(
			'name'               => 'North Korean Won',
			'code'               => 'KPW',
			'number'             => 408,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₩',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KRW' => array(
			'name'               => 'Won',
			'code'               => 'KRW',
			'number'             => 410,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => '₩',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KWD' => array(
			'name'               => 'Kuwaiti Dinar',
			'code'               => 'KWD',
			'number'             => 414,
			'precision'          => 3,
			'subunit'            => 1000,
			'symbol'             => 'د.ك',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KYD' => array(
			'name'               => 'Cayman Islands Dollar',
			'code'               => 'KYD',
			'number'             => 136,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'KZT' => array(
			'name'               => 'Tenge',
			'code'               => 'KZT',
			'number'             => 398,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '〒',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'LAK' => array(
			'name'               => 'Kip',
			'code'               => 'LAK',
			'number'             => 418,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₭',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'LBP' => array(
			'name'               => 'Lebanese Pound',
			'code'               => 'LBP',
			'number'             => 422,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ل.ل',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'LKR' => array(
			'name'               => 'Sri Lanka Rupee',
			'code'               => 'LKR',
			'number'             => 144,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₨',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'LRD' => array(
			'name'               => 'Liberian Dollar',
			'code'               => 'LRD',
			'number'             => 430,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'LSL' => array(
			'name'               => 'Loti',
			'code'               => 'LSL',
			'number'             => 426,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'L',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'LTL' => array(
			'name'               => 'Lithuanian Litas',
			'code'               => 'LTL',
			'number'             => 440,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Lt',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'LVL' => array(
			'name'               => 'Latvian Lats',
			'code'               => 'LVL',
			'number'             => 428,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Ls',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'LYD' => array(
			'name'               => 'Libyan Dinar',
			'code'               => 'LYD',
			'number'             => 434,
			'precision'          => 3,
			'subunit'            => 1000,
			'symbol'             => 'ل.د',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MAD' => array(
			'name'               => 'Moroccan Dirham',
			'code'               => 'MAD',
			'number'             => 504,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'د.م.',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MDL' => array(
			'name'               => 'Moldovan Leu',
			'code'               => 'MDL',
			'number'             => 498,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'L',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MGA' => array(
			'name'               => 'Malagasy Ariary',
			'code'               => 'MGA',
			'number'             => 969,
			'precision'          => 2,
			'subunit'            => 5,
			'symbol'             => 'Ar',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MKD' => array(
			'name'               => 'Denar',
			'code'               => 'MKD',
			'number'             => 807,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ден',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MMK' => array(
			'name'               => 'Kyat',
			'code'               => 'MMK',
			'number'             => 104,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'K',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MNT' => array(
			'name'               => 'Tugrik',
			'code'               => 'MNT',
			'number'             => 496,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₮',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MOP' => array(
			'name'               => 'Pataca',
			'code'               => 'MOP',
			'number'             => 446,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'P',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MRO' => array(
			'name'               => 'Ouguiya',
			'code'               => 'MRO',
			'number'             => 478,
			'precision'          => 2,
			'subunit'            => 5,
			'symbol'             => 'UM',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MUR' => array(
			'name'               => 'Mauritius Rupee',
			'code'               => 'MUR',
			'number'             => 480,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₨',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MVR' => array(
			'name'               => 'Rufiyaa',
			'code'               => 'MVR',
			'number'             => 462,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'MVR',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MWK' => array(
			'name'               => 'Kwacha',
			'code'               => 'MWK',
			'number'             => 454,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'MK',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MXN' => array(
			'name'               => 'Mexican Peso',
			'code'               => 'MXN',
			'number'             => 484,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MYR' => array(
			'name'               => 'Malaysian Ringgit',
			'code'               => 'MYR',
			'number'             => 458,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'RM',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'MZN' => array(
			'name'               => 'Mozambique Metical',
			'code'               => 'MZN',
			'number'             => 943,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'MTn',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'NAD' => array(
			'name'               => 'Namibia Dollar',
			'code'               => 'NAD',
			'number'             => 516,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'NGN' => array(
			'name'               => 'Naira',
			'code'               => 'NGN',
			'number'             => 566,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₦',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'NIO' => array(
			'name'               => 'Cordoba Oro',
			'code'               => 'NIO',
			'number'             => 558,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'C$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'NOK' => array(
			'name'               => 'Norwegian Krone',
			'code'               => 'NOK',
			'number'             => 578,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'kr',
			'position'           => 'after',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'NPR' => array(
			'name'               => 'Nepalese Rupee',
			'code'               => 'NPR',
			'number'             => 524,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₨',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'NZD' => array(
			'name'               => 'New Zealand Dollar',
			'code'               => 'NZD',
			'number'             => 554,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'OMR' => array(
			'name'               => 'Rial Omani',
			'code'               => 'OMR',
			'number'             => 512,
			'precision'          => 3,
			'subunit'            => 1000,
			'symbol'             => 'ر.ع.',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'PAB' => array(
			'name'               => 'Balboa',
			'code'               => 'PAB',
			'number'             => 590,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'B/.',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'PEN' => array(
			'name'               => 'Sol',
			'code'               => 'PEN',
			'number'             => 604,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'S/',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'PGK' => array(
			'name'               => 'Kina',
			'code'               => 'PGK',
			'number'             => 598,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'K',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'PHP' => array(
			'name'               => 'Philippine Peso',
			'code'               => 'PHP',
			'number'             => 608,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₱',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'PKR' => array(
			'name'               => 'Pakistan Rupee',
			'code'               => 'PKR',
			'number'             => 586,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₨',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'PLN' => array(
			'name'               => 'Zloty',
			'code'               => 'PLN',
			'number'             => 985,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'zł',
			'position'           => 'after',
			'decimal_separator'  => ',',
			'thousand_separator' => ' ',
		),

		'PYG' => array(
			'name'               => 'Guarani',
			'code'               => 'PYG',
			'number'             => 600,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => '₲',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'QAR' => array(
			'name'               => 'Qatari Rial',
			'code'               => 'QAR',
			'number'             => 634,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ر.ق',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'RON' => array(
			'name'               => 'New Romanian Leu',
			'code'               => 'RON',
			'number'             => 946,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Lei',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'RSD' => array(
			'name'               => 'Serbian Dinar',
			'code'               => 'RSD',
			'number'             => 941,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'РСД',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'RUB' => array(
			'name'               => 'Russian Ruble',
			'code'               => 'RUB',
			'number'             => 643,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₽',
			'position'           => 'after',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'RWF' => array(
			'name'               => 'Rwanda Franc',
			'code'               => 'RWF',
			'number'             => 646,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'FRw',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SAR' => array(
			'name'               => 'Saudi Riyal',
			'code'               => 'SAR',
			'number'             => 682,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ر.س',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SBD' => array(
			'name'               => 'Solomon Islands Dollar',
			'code'               => 'SBD',
			'number'             => 90,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SCR' => array(
			'name'               => 'Seychelles Rupee',
			'code'               => 'SCR',
			'number'             => 690,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₨',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SDG' => array(
			'name'               => 'Sudanese Pound',
			'code'               => 'SDG',
			'number'             => 938,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '£',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SEK' => array(
			'name'               => 'Swedish Krona',
			'code'               => 'SEK',
			'number'             => 752,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'kr',
			'position'           => 'after',
			'decimal_separator'  => ',',
			'thousand_separator' => ' ',
		),

		'SGD' => array(
			'name'               => 'Singapore Dollar',
			'code'               => 'SGD',
			'number'             => 702,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SHP' => array(
			'name'               => 'Saint Helena Pound',
			'code'               => 'SHP',
			'number'             => 654,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '£',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SLL' => array(
			'name'               => 'Leone',
			'code'               => 'SLL',
			'number'             => 694,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Le',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SOS' => array(
			'name'               => 'Somali Shilling',
			'code'               => 'SOS',
			'number'             => 706,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Sh',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SRD' => array(
			'name'               => 'Surinam Dollar',
			'code'               => 'SRD',
			'number'             => 968,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SSP' => array(
			'name'               => 'South Sudanese Pound',
			'code'               => 'SSP',
			'number'             => 728,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '£',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'STD' => array(
			'name'               => 'Dobra',
			'code'               => 'STD',
			'number'             => 678,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Db',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SVC' => array(
			'name'               => 'El Salvador Colon',
			'code'               => 'SVC',
			'number'             => 222,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₡',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SYP' => array(
			'name'               => 'Syrian Pound',
			'code'               => 'SYP',
			'number'             => 760,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '£S',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'SZL' => array(
			'name'               => 'Lilangeni',
			'code'               => 'SZL',
			'number'             => 748,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'E',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'THB' => array(
			'name'               => 'Baht',
			'code'               => 'THB',
			'number'             => 764,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '฿',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'TJS' => array(
			'name'               => 'Somoni',
			'code'               => 'TJS',
			'number'             => 972,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ЅМ',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'TMT' => array(
			'name'               => 'Turkmenistan New Manat',
			'code'               => 'TMT',
			'number'             => 934,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'T',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'TND' => array(
			'name'               => 'Tunisian Dinar',
			'code'               => 'TND',
			'number'             => 788,
			'precision'          => 3,
			'subunit'            => 1000,
			'symbol'             => 'د.ت',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'TOP' => array(
			'name'               => 'Pa’anga',
			'code'               => 'TOP',
			'number'             => 776,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'T$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'TRY' => array(
			'name'               => 'Turkish Lira',
			'code'               => 'TRY',
			'number'             => 949,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₺',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'TTD' => array(
			'name'               => 'Trinidad and Tobago Dollar',
			'code'               => 'TTD',
			'number'             => 780,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'TWD' => array(
			'name'               => 'New Taiwan Dollar',
			'code'               => 'TWD',
			'number'             => 901,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'TZS' => array(
			'name'               => 'Tanzanian Shilling',
			'code'               => 'TZS',
			'number'             => 834,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Sh',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'UAH' => array(
			'name'               => 'Hryvnia',
			'code'               => 'UAH',
			'number'             => 980,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '₴',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'UGX' => array(
			'name'               => 'Uganda Shilling',
			'code'               => 'UGX',
			'number'             => 800,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'USh',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'USD' => array(
			'name'               => 'US Dollar',
			'code'               => 'USD',
			'number'             => 840,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'UYU' => array(
			'name'               => 'Peso Uruguayo',
			'code'               => 'UYU',
			'number'             => 858,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'UZS' => array(
			'name'               => 'Uzbekistan Sum',
			'code'               => 'UZS',
			'number'             => 860,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => null,
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'VEF' => array(
			'name'               => 'Bolivar',
			'code'               => 'VEF',
			'number'             => 937,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'Bs F',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'VND' => array(
			'name'               => 'Dong',
			'code'               => 'VND',
			'number'             => 704,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => '₫',
			'position'           => 'before',
			'decimal_separator'  => ',',
			'thousand_separator' => '.',
		),

		'VUV' => array(
			'name'               => 'Vatu',
			'code'               => 'VUV',
			'number'             => 548,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Vt',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'WST' => array(
			'name'               => 'Tala',
			'code'               => 'WST',
			'number'             => 882,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'T',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'XAF' => array(
			'name'               => 'CFA Franc BEAC',
			'code'               => 'XAF',
			'number'             => 950,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Fr',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'XAG' => array(
			'name'               => 'Silver',
			'code'               => 'XAG',
			'number'             => 961,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'oz t',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'XAU' => array(
			'name'               => 'Gold',
			'code'               => 'XAU',
			'number'             => 959,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'oz t',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'XCD' => array(
			'name'               => 'East Caribbean Dollar',
			'code'               => 'XCD',
			'number'             => 951,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'XDR' => array(
			'name'               => 'SDR (Special Drawing Right)',
			'code'               => 'XDR',
			'number'             => 960,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'SDR',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'XOF' => array(
			'name'               => 'CFA Franc BCEAO',
			'code'               => 'XOF',
			'number'             => 952,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Fr',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'XPF' => array(
			'name'               => 'CFP Franc',
			'code'               => 'XPF',
			'number'             => 953,
			'precision'          => 0,
			'subunit'            => 1,
			'symbol'             => 'Fr',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'YER' => array(
			'name'               => 'Yemeni Rial',
			'code'               => 'YER',
			'number'             => 886,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '﷼',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ZAR' => array(
			'name'               => 'Rand',
			'code'               => 'ZAR',
			'number'             => 710,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'R',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ZMW' => array(
			'name'               => 'Zambian Kwacha',
			'code'               => 'ZMW',
			'number'             => 967,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => 'ZK',
			'position'           => 'after',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),

		'ZWL' => array(
			'name'               => 'Zimbabwe Dollar',
			'code'               => 'ZWL',
			'number'             => 932,
			'precision'          => 2,
			'subunit'            => 100,
			'symbol'             => '$',
			'position'           => 'before',
			'decimal_separator'  => '.',
			'thousand_separator' => ',',
		),
	);

	return apply_filters( 'eaccounting_global_currencies', $currencies );
}


/**
 * Get all countries
 * since 1.0.0
 *
 * @return array
 */
function eaccounting_get_countries() {
	$countries = array(
		'AF' => 'Afghanistan',
		'AL' => 'Albania',
		'DZ' => 'Algeria',
		'AS' => 'American Samoa',
		'AD' => 'Andorra',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antarctica',
		'AG' => 'Antigua and Barbuda',
		'AR' => 'Argentina',
		'AM' => 'Armenia',
		'AW' => 'Aruba',
		'AU' => 'Australia',
		'AT' => 'Austria',
		'AZ' => 'Azerbaijan',
		'BS' => 'Bahamas',
		'BH' => 'Bahrain',
		'BD' => 'Bangladesh',
		'BB' => 'Barbados',
		'BY' => 'Belarus',
		'BE' => 'Belgium',
		'BZ' => 'Belize',
		'BJ' => 'Benin',
		'BM' => 'Bermuda',
		'BT' => 'Bhutan',
		'BO' => 'Bolivia',
		'BA' => 'Bosnia and Herzegovina',
		'BW' => 'Botswana',
		'BV' => 'Bouvet Island',
		'BR' => 'Brazil',
		'IO' => 'British Indian Ocean Territory',
		'BN' => 'Brunei Darussalam',
		'BG' => 'Bulgaria',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'KH' => 'Cambodia',
		'CM' => 'Cameroon',
		'CA' => 'Canada',
		'CV' => 'Cape Verde',
		'KY' => 'Cayman Islands',
		'CF' => 'Central African Republic',
		'TD' => 'Chad',
		'CL' => 'Chile',
		'CN' => 'China',
		'CX' => 'Christmas Island',
		'CC' => 'Cocos (Keeling) Islands',
		'CO' => 'Colombia',
		'KM' => 'Comoros',
		'CG' => 'Congo',
		'CD' => 'Congo, the Democratic Republic of the',
		'CK' => 'Cook Islands',
		'CR' => 'Costa Rica',
		'CI' => "Cote D'Ivoire",
		'HR' => 'Croatia',
		'CU' => 'Cuba',
		'CY' => 'Cyprus',
		'CZ' => 'Czech Republic',
		'DK' => 'Denmark',
		'DJ' => 'Djibouti',
		'DM' => 'Dominica',
		'DO' => 'Dominican Republic',
		'EC' => 'Ecuador',
		'EG' => 'Egypt',
		'SV' => 'El Salvador',
		'GQ' => 'Equatorial Guinea',
		'ER' => 'Eritrea',
		'EE' => 'Estonia',
		'ET' => 'Ethiopia',
		'FK' => 'Falkland Islands (Malvinas)',
		'FO' => 'Faroe Islands',
		'FJ' => 'Fiji',
		'FI' => 'Finland',
		'FR' => 'France',
		'GF' => 'French Guiana',
		'PF' => 'French Polynesia',
		'TF' => 'French Southern Territories',
		'GA' => 'Gabon',
		'GM' => 'Gambia',
		'GE' => 'Georgia',
		'DE' => 'Germany',
		'GH' => 'Ghana',
		'GI' => 'Gibraltar',
		'GR' => 'Greece',
		'GL' => 'Greenland',
		'GD' => 'Grenada',
		'GP' => 'Guadeloupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GN' => 'Guinea',
		'GW' => 'Guinea-Bissau',
		'GY' => 'Guyana',
		'HT' => 'Haiti',
		'HM' => 'Heard Island and Mcdonald Islands',
		'VA' => 'Holy See (Vatican City State)',
		'HN' => 'Honduras',
		'HK' => 'Hong Kong',
		'HU' => 'Hungary',
		'IS' => 'Iceland',
		'IN' => 'India',
		'ID' => 'Indonesia',
		'IR' => 'Iran, Islamic Republic of',
		'IQ' => 'Iraq',
		'IE' => 'Ireland',
		'IL' => 'Israel',
		'IT' => 'Italy',
		'JM' => 'Jamaica',
		'JP' => 'Japan',
		'JO' => 'Jordan',
		'KZ' => 'Kazakhstan',
		'KE' => 'Kenya',
		'KI' => 'Kiribati',
		'KP' => "Korea, Democratic People's Republic of",
		'KR' => 'Korea, Republic of',
		'KW' => 'Kuwait',
		'KG' => 'Kyrgyzstan',
		'LA' => "Lao People's Democratic Republic",
		'LV' => 'Latvia',
		'LB' => 'Lebanon',
		'LS' => 'Lesotho',
		'LR' => 'Liberia',
		'LY' => 'Libyan Arab Jamahiriya',
		'LI' => 'Liechtenstein',
		'LT' => 'Lithuania',
		'LU' => 'Luxembourg',
		'MO' => 'Macao',
		'MK' => 'Macedonia, the Former Yugoslav Republic of',
		'MG' => 'Madagascar',
		'MW' => 'Malawi',
		'MY' => 'Malaysia',
		'MV' => 'Maldives',
		'ML' => 'Mali',
		'MT' => 'Malta',
		'MH' => 'Marshall Islands',
		'MQ' => 'Martinique',
		'MR' => 'Mauritania',
		'MU' => 'Mauritius',
		'YT' => 'Mayotte',
		'MX' => 'Mexico',
		'FM' => 'Micronesia, Federated States of',
		'MD' => 'Moldova, Republic of',
		'MC' => 'Monaco',
		'MN' => 'Mongolia',
		'MS' => 'Montserrat',
		'MA' => 'Morocco',
		'MZ' => 'Mozambique',
		'MM' => 'Myanmar',
		'NA' => 'Namibia',
		'NR' => 'Nauru',
		'NP' => 'Nepal',
		'NL' => 'Netherlands',
		'AN' => 'Netherlands Antilles',
		'NC' => 'New Caledonia',
		'NZ' => 'New Zealand',
		'NI' => 'Nicaragua',
		'NE' => 'Niger',
		'NG' => 'Nigeria',
		'NU' => 'Niue',
		'NF' => 'Norfolk Island',
		'MP' => 'Northern Mariana Islands',
		'NO' => 'Norway',
		'OM' => 'Oman',
		'PK' => 'Pakistan',
		'PW' => 'Palau',
		'PS' => 'Palestinian Territory, Occupied',
		'PA' => 'Panama',
		'PG' => 'Papua New Guinea',
		'PY' => 'Paraguay',
		'PE' => 'Peru',
		'PH' => 'Philippines',
		'PN' => 'Pitcairn',
		'PL' => 'Poland',
		'PT' => 'Portugal',
		'PR' => 'Puerto Rico',
		'QA' => 'Qatar',
		'RE' => 'Reunion',
		'RO' => 'Romania',
		'RU' => 'Russian Federation',
		'RW' => 'Rwanda',
		'SH' => 'Saint Helena',
		'KN' => 'Saint Kitts and Nevis',
		'LC' => 'Saint Lucia',
		'PM' => 'Saint Pierre and Miquelon',
		'VC' => 'Saint Vincent and the Grenadines',
		'WS' => 'Samoa',
		'SM' => 'San Marino',
		'ST' => 'Sao Tome and Principe',
		'SA' => 'Saudi Arabia',
		'SN' => 'Senegal',
		'CS' => 'Serbia and Montenegro',
		'SC' => 'Seychelles',
		'SL' => 'Sierra Leone',
		'SG' => 'Singapore',
		'SK' => 'Slovakia',
		'SI' => 'Slovenia',
		'SB' => 'Solomon Islands',
		'SO' => 'Somalia',
		'ZA' => 'South Africa',
		'GS' => 'South Georgia and the South Sandwich Islands',
		'ES' => 'Spain',
		'LK' => 'Sri Lanka',
		'SD' => 'Sudan',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard and Jan Mayen',
		'SZ' => 'Swaziland',
		'SE' => 'Sweden',
		'CH' => 'Switzerland',
		'SY' => 'Syrian Arab Republic',
		'TW' => 'Taiwan, Province of China',
		'TJ' => 'Tajikistan',
		'TZ' => 'Tanzania, United Republic of',
		'TH' => 'Thailand',
		'TL' => 'Timor-Leste',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinidad and Tobago',
		'TN' => 'Tunisia',
		'TR' => 'Turkey',
		'TM' => 'Turkmenistan',
		'TC' => 'Turks and Caicos Islands',
		'TV' => 'Tuvalu',
		'UG' => 'Uganda',
		'UA' => 'Ukraine',
		'AE' => 'United Arab Emirates',
		'GB' => 'United Kingdom',
		'US' => 'United States',
		'UM' => 'United States Minor Outlying Islands',
		'UY' => 'Uruguay',
		'UZ' => 'Uzbekistan',
		'VU' => 'Vanuatu',
		'VE' => 'Venezuela',
		'VN' => 'Viet Nam',
		'VG' => 'Virgin Islands, British',
		'VI' => 'Virgin Islands, U.s.',
		'WF' => 'Wallis and Futuna',
		'EH' => 'Western Sahara',
		'YE' => 'Yemen',
		'ZM' => 'Zambia',
		'ZW' => 'Zimbabwe',
	);

	return apply_filters( 'eaccounting_countries', $countries );
}
