<?php
defined( 'ABSPATH' ) || exit();

/**
 * Generate a random color
 * since 1.0.0
 * @return string
 */
function eaccounting_get_random_hex_color() {
	return '#' . str_pad( dechex( mt_rand( 0, 0xFFFFFF ) ), 6, '0', STR_PAD_LEFT );
}

/**
 * Get all countries
 * since 1.0.0
 *
 * @return array
 */
function eaccounting_get_countries() {
	$countries = array(
		"AF" => "Afghanistan",
		"AL" => "Albania",
		"DZ" => "Algeria",
		"AS" => "American Samoa",
		"AD" => "Andorra",
		"AO" => "Angola",
		"AI" => "Anguilla",
		"AQ" => "Antarctica",
		"AG" => "Antigua and Barbuda",
		"AR" => "Argentina",
		"AM" => "Armenia",
		"AW" => "Aruba",
		"AU" => "Australia",
		"AT" => "Austria",
		"AZ" => "Azerbaijan",
		"BS" => "Bahamas",
		"BH" => "Bahrain",
		"BD" => "Bangladesh",
		"BB" => "Barbados",
		"BY" => "Belarus",
		"BE" => "Belgium",
		"BZ" => "Belize",
		"BJ" => "Benin",
		"BM" => "Bermuda",
		"BT" => "Bhutan",
		"BO" => "Bolivia",
		"BA" => "Bosnia and Herzegovina",
		"BW" => "Botswana",
		"BV" => "Bouvet Island",
		"BR" => "Brazil",
		"IO" => "British Indian Ocean Territory",
		"BN" => "Brunei Darussalam",
		"BG" => "Bulgaria",
		"BF" => "Burkina Faso",
		"BI" => "Burundi",
		"KH" => "Cambodia",
		"CM" => "Cameroon",
		"CA" => "Canada",
		"CV" => "Cape Verde",
		"KY" => "Cayman Islands",
		"CF" => "Central African Republic",
		"TD" => "Chad",
		"CL" => "Chile",
		"CN" => "China",
		"CX" => "Christmas Island",
		"CC" => "Cocos (Keeling) Islands",
		"CO" => "Colombia",
		"KM" => "Comoros",
		"CG" => "Congo",
		"CD" => "Congo, the Democratic Republic of the",
		"CK" => "Cook Islands",
		"CR" => "Costa Rica",
		"CI" => "Cote D'Ivoire",
		"HR" => "Croatia",
		"CU" => "Cuba",
		"CY" => "Cyprus",
		"CZ" => "Czech Republic",
		"DK" => "Denmark",
		"DJ" => "Djibouti",
		"DM" => "Dominica",
		"DO" => "Dominican Republic",
		"EC" => "Ecuador",
		"EG" => "Egypt",
		"SV" => "El Salvador",
		"GQ" => "Equatorial Guinea",
		"ER" => "Eritrea",
		"EE" => "Estonia",
		"ET" => "Ethiopia",
		"FK" => "Falkland Islands (Malvinas)",
		"FO" => "Faroe Islands",
		"FJ" => "Fiji",
		"FI" => "Finland",
		"FR" => "France",
		"GF" => "French Guiana",
		"PF" => "French Polynesia",
		"TF" => "French Southern Territories",
		"GA" => "Gabon",
		"GM" => "Gambia",
		"GE" => "Georgia",
		"DE" => "Germany",
		"GH" => "Ghana",
		"GI" => "Gibraltar",
		"GR" => "Greece",
		"GL" => "Greenland",
		"GD" => "Grenada",
		"GP" => "Guadeloupe",
		"GU" => "Guam",
		"GT" => "Guatemala",
		"GN" => "Guinea",
		"GW" => "Guinea-Bissau",
		"GY" => "Guyana",
		"HT" => "Haiti",
		"HM" => "Heard Island and Mcdonald Islands",
		"VA" => "Holy See (Vatican City State)",
		"HN" => "Honduras",
		"HK" => "Hong Kong",
		"HU" => "Hungary",
		"IS" => "Iceland",
		"IN" => "India",
		"ID" => "Indonesia",
		"IR" => "Iran, Islamic Republic of",
		"IQ" => "Iraq",
		"IE" => "Ireland",
		"IL" => "Israel",
		"IT" => "Italy",
		"JM" => "Jamaica",
		"JP" => "Japan",
		"JO" => "Jordan",
		"KZ" => "Kazakhstan",
		"KE" => "Kenya",
		"KI" => "Kiribati",
		"KP" => "Korea, Democratic People's Republic of",
		"KR" => "Korea, Republic of",
		"KW" => "Kuwait",
		"KG" => "Kyrgyzstan",
		"LA" => "Lao People's Democratic Republic",
		"LV" => "Latvia",
		"LB" => "Lebanon",
		"LS" => "Lesotho",
		"LR" => "Liberia",
		"LY" => "Libyan Arab Jamahiriya",
		"LI" => "Liechtenstein",
		"LT" => "Lithuania",
		"LU" => "Luxembourg",
		"MO" => "Macao",
		"MK" => "Macedonia, the Former Yugoslav Republic of",
		"MG" => "Madagascar",
		"MW" => "Malawi",
		"MY" => "Malaysia",
		"MV" => "Maldives",
		"ML" => "Mali",
		"MT" => "Malta",
		"MH" => "Marshall Islands",
		"MQ" => "Martinique",
		"MR" => "Mauritania",
		"MU" => "Mauritius",
		"YT" => "Mayotte",
		"MX" => "Mexico",
		"FM" => "Micronesia, Federated States of",
		"MD" => "Moldova, Republic of",
		"MC" => "Monaco",
		"MN" => "Mongolia",
		"MS" => "Montserrat",
		"MA" => "Morocco",
		"MZ" => "Mozambique",
		"MM" => "Myanmar",
		"NA" => "Namibia",
		"NR" => "Nauru",
		"NP" => "Nepal",
		"NL" => "Netherlands",
		"AN" => "Netherlands Antilles",
		"NC" => "New Caledonia",
		"NZ" => "New Zealand",
		"NI" => "Nicaragua",
		"NE" => "Niger",
		"NG" => "Nigeria",
		"NU" => "Niue",
		"NF" => "Norfolk Island",
		"MP" => "Northern Mariana Islands",
		"NO" => "Norway",
		"OM" => "Oman",
		"PK" => "Pakistan",
		"PW" => "Palau",
		"PS" => "Palestinian Territory, Occupied",
		"PA" => "Panama",
		"PG" => "Papua New Guinea",
		"PY" => "Paraguay",
		"PE" => "Peru",
		"PH" => "Philippines",
		"PN" => "Pitcairn",
		"PL" => "Poland",
		"PT" => "Portugal",
		"PR" => "Puerto Rico",
		"QA" => "Qatar",
		"RE" => "Reunion",
		"RO" => "Romania",
		"RU" => "Russian Federation",
		"RW" => "Rwanda",
		"SH" => "Saint Helena",
		"KN" => "Saint Kitts and Nevis",
		"LC" => "Saint Lucia",
		"PM" => "Saint Pierre and Miquelon",
		"VC" => "Saint Vincent and the Grenadines",
		"WS" => "Samoa",
		"SM" => "San Marino",
		"ST" => "Sao Tome and Principe",
		"SA" => "Saudi Arabia",
		"SN" => "Senegal",
		"CS" => "Serbia and Montenegro",
		"SC" => "Seychelles",
		"SL" => "Sierra Leone",
		"SG" => "Singapore",
		"SK" => "Slovakia",
		"SI" => "Slovenia",
		"SB" => "Solomon Islands",
		"SO" => "Somalia",
		"ZA" => "South Africa",
		"GS" => "South Georgia and the South Sandwich Islands",
		"ES" => "Spain",
		"LK" => "Sri Lanka",
		"SD" => "Sudan",
		"SR" => "Suriname",
		"SJ" => "Svalbard and Jan Mayen",
		"SZ" => "Swaziland",
		"SE" => "Sweden",
		"CH" => "Switzerland",
		"SY" => "Syrian Arab Republic",
		"TW" => "Taiwan, Province of China",
		"TJ" => "Tajikistan",
		"TZ" => "Tanzania, United Republic of",
		"TH" => "Thailand",
		"TL" => "Timor-Leste",
		"TG" => "Togo",
		"TK" => "Tokelau",
		"TO" => "Tonga",
		"TT" => "Trinidad and Tobago",
		"TN" => "Tunisia",
		"TR" => "Turkey",
		"TM" => "Turkmenistan",
		"TC" => "Turks and Caicos Islands",
		"TV" => "Tuvalu",
		"UG" => "Uganda",
		"UA" => "Ukraine",
		"AE" => "United Arab Emirates",
		"GB" => "United Kingdom",
		"US" => "United States",
		"UM" => "United States Minor Outlying Islands",
		"UY" => "Uruguay",
		"UZ" => "Uzbekistan",
		"VU" => "Vanuatu",
		"VE" => "Venezuela",
		"VN" => "Viet Nam",
		"VG" => "Virgin Islands, British",
		"VI" => "Virgin Islands, U.s.",
		"WF" => "Wallis and Futuna",
		"EH" => "Western Sahara",
		"YE" => "Yemen",
		"ZM" => "Zambia",
		"ZW" => "Zimbabwe"
	);

	return apply_filters( 'eaccounting_countries', $countries );
}

/**
 * @return mixed|void
 * @since 1.0.2
 */
function eaccounting_get_global_currencies() {
	$config = array(
		'AED' => [
			'name'              => 'UAE Dirham',
			'code'              => 'AED',
			'number'            => 784,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'د.إ',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'AFN' => [
			'name'              => 'Afghani',
			'code'              => 'AFN',
			'number'            => 971,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '؋',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ALL' => [
			'name'              => 'Lek',
			'code'              => 'ALL',
			'number'            => 8,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'L',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'AMD' => [
			'name'              => 'Armenian Dram',
			'code'              => 'AMD',
			'number'            => 51,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'դր.',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ANG' => [
			'name'              => 'Netherlands Antillean Guilder',
			'code'              => 'ANG',
			'number'            => 532,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ƒ',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'AOA' => [
			'name'              => 'Kwanza',
			'code'              => 'AOA',
			'number'            => 973,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Kz',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ARS' => [
			'name'              => 'Argentine Peso',
			'code'              => 'ARS',
			'number'            => 32,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'AUD' => [
			'name'              => 'Australian Dollar',
			'code'              => 'AUD',
			'number'            => 36,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ' ',
		],

		'AWG' => [
			'name'              => 'Aruban Florin',
			'code'              => 'AWG',
			'number'            => 533,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ƒ',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'AZN' => [
			'name'              => 'Azerbaijanian Manat',
			'code'              => 'AZN',
			'number'            => 944,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₼',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BAM' => [
			'name'              => 'Convertible Mark',
			'code'              => 'BAM',
			'number'            => 977,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'КМ',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BBD' => [
			'name'              => 'Barbados Dollar',
			'code'              => 'BBD',
			'number'            => 52,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BDT' => [
			'name'              => 'Taka',
			'code'              => 'BDT',
			'number'            => 50,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '৳',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BGN' => [
			'name'              => 'Bulgarian Lev',
			'code'              => 'BGN',
			'number'            => 975,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'лв',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BHD' => [
			'name'              => 'Bahraini Dinar',
			'code'              => 'BHD',
			'number'            => 48,
			'precision'         => 3,
			'subunit'           => 1000,
			'symbol'            => 'ب.د',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BIF' => [
			'name'              => 'Burundi Franc',
			'code'              => 'BIF',
			'number'            => 108,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Fr',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BMD' => [
			'name'              => 'Bermudian Dollar',
			'code'              => 'BMD',
			'number'            => 60,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BND' => [
			'name'              => 'Brunei Dollar',
			'code'              => 'BND',
			'number'            => 96,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BOB' => [
			'name'              => 'Boliviano',
			'code'              => 'BOB',
			'number'            => 68,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Bs.',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BOV' => [
			'name'              => 'Mvdol',
			'code'              => 'BOV',
			'number'            => 984,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Bs.',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BRL' => [
			'name'              => 'Brazilian Real',
			'code'              => 'BRL',
			'number'            => 986,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'R$',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'BSD' => [
			'name'              => 'Bahamian Dollar',
			'code'              => 'BSD',
			'number'            => 44,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BTN' => [
			'name'              => 'Ngultrum',
			'code'              => 'BTN',
			'number'            => 64,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Nu.',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BWP' => [
			'name'              => 'Pula',
			'code'              => 'BWP',
			'number'            => 72,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'P',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'BYN' => [
			'name'              => 'Belarussian Ruble',
			'code'              => 'BYN',
			'number'            => 974,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Br',
			'position'          => 'after',
			'decimalSeparator'  => ',',
			'thousandSeparator' => ' ',
		],

		'BZD' => [
			'name'              => 'Belize Dollar',
			'code'              => 'BZD',
			'number'            => 84,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'CAD' => [
			'name'              => 'Canadian Dollar',
			'code'              => 'CAD',
			'number'            => 124,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'CDF' => [
			'name'              => 'Congolese Franc',
			'code'              => 'CDF',
			'number'            => 976,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Fr',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'CHF' => [
			'name'              => 'Swiss Franc',
			'code'              => 'CHF',
			'number'            => 756,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'CHF',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'CLF' => [
			'name'              => 'Unidades de fomento',
			'code'              => 'CLF',
			'number'            => 990,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'UF',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'CLP' => [
			'name'              => 'Chilean Peso',
			'code'              => 'CLP',
			'number'            => 152,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'CNY' => [
			'name'              => 'Yuan Renminbi',
			'code'              => 'CNY',
			'number'            => 156,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '¥',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'COP' => [
			'name'              => 'Colombian Peso',
			'code'              => 'COP',
			'number'            => 170,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'CRC' => [
			'name'              => 'Costa Rican Colon',
			'code'              => 'CRC',
			'number'            => 188,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₡',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'CUC' => [
			'name'              => 'Peso Convertible',
			'code'              => 'CUC',
			'number'            => 931,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'CUP' => [
			'name'              => 'Cuban Peso',
			'code'              => 'CUP',
			'number'            => 192,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'CVE' => [
			'name'              => 'Cape Verde Escudo',
			'code'              => 'CVE',
			'number'            => 132,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'CZK' => [
			'name'              => 'Czech Koruna',
			'code'              => 'CZK',
			'number'            => 203,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Kč',
			'position'          => 'after',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'DJF' => [
			'name'              => 'Djibouti Franc',
			'code'              => 'DJF',
			'number'            => 262,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Fdj',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'DKK' => [
			'name'              => 'Danish Krone',
			'code'              => 'DKK',
			'number'            => 208,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'kr',
			'position'          => 'after',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'DOP' => [
			'name'              => 'Dominican Peso',
			'code'              => 'DOP',
			'number'            => 214,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'DZD' => [
			'name'              => 'Algerian Dinar',
			'code'              => 'DZD',
			'number'            => 12,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'د.ج',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'EGP' => [
			'name'              => 'Egyptian Pound',
			'code'              => 'EGP',
			'number'            => 818,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ج.م',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ERN' => [
			'name'              => 'Nakfa',
			'code'              => 'ERN',
			'number'            => 232,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Nfk',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ETB' => [
			'name'              => 'Ethiopian Birr',
			'code'              => 'ETB',
			'number'            => 230,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Br',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'EUR' => [
			'name'              => 'Euro',
			'code'              => 'EUR',
			'number'            => 978,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '€',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'FJD' => [
			'name'              => 'Fiji Dollar',
			'code'              => 'FJD',
			'number'            => 242,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'FKP' => [
			'name'              => 'Falkland Islands Pound',
			'code'              => 'FKP',
			'number'            => 238,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '£',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'GBP' => [
			'name'              => 'Pound Sterling',
			'code'              => 'GBP',
			'number'            => 826,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '£',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'GEL' => [
			'name'              => 'Lari',
			'code'              => 'GEL',
			'number'            => 981,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ლ',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'GHS' => [
			'name'              => 'Ghana Cedi',
			'code'              => 'GHS',
			'number'            => 936,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₵',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'GIP' => [
			'name'              => 'Gibraltar Pound',
			'code'              => 'GIP',
			'number'            => 292,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '£',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'GMD' => [
			'name'              => 'Dalasi',
			'code'              => 'GMD',
			'number'            => 270,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'D',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'GNF' => [
			'name'              => 'Guinea Franc',
			'code'              => 'GNF',
			'number'            => 324,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Fr',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'GTQ' => [
			'name'              => 'Quetzal',
			'code'              => 'GTQ',
			'number'            => 320,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Q',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'GYD' => [
			'name'              => 'Guyana Dollar',
			'code'              => 'GYD',
			'number'            => 328,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'HKD' => [
			'name'              => 'Hong Kong Dollar',
			'code'              => 'HKD',
			'number'            => 344,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'HNL' => [
			'name'              => 'Lempira',
			'code'              => 'HNL',
			'number'            => 340,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'L',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'HRK' => [
			'name'              => 'Croatian Kuna',
			'code'              => 'HRK',
			'number'            => 191,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'kn',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'HTG' => [
			'name'              => 'Gourde',
			'code'              => 'HTG',
			'number'            => 332,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'G',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'HUF' => [
			'name'              => 'Forint',
			'code'              => 'HUF',
			'number'            => 348,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Ft',
			'position'          => 'after',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'IDR' => [
			'name'              => 'Rupiah',
			'code'              => 'IDR',
			'number'            => 360,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Rp',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'ILS' => [
			'name'              => 'New Israeli Sheqel',
			'code'              => 'ILS',
			'number'            => 376,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₪',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'INR' => [
			'name'              => 'Indian Rupee',
			'code'              => 'INR',
			'number'            => 356,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₹',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'IQD' => [
			'name'              => 'Iraqi Dinar',
			'code'              => 'IQD',
			'number'            => 368,
			'precision'         => 3,
			'subunit'           => 1000,
			'symbol'            => 'ع.د',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'IRR' => [
			'name'              => 'Iranian Rial',
			'code'              => 'IRR',
			'number'            => 364,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '﷼',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ISK' => [
			'name'              => 'Iceland Krona',
			'code'              => 'ISK',
			'number'            => 352,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'kr',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'JMD' => [
			'name'              => 'Jamaican Dollar',
			'code'              => 'JMD',
			'number'            => 388,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'JOD' => [
			'name'              => 'Jordanian Dinar',
			'code'              => 'JOD',
			'number'            => 400,
			'precision'         => 3,
			'subunit'           => 100,
			'symbol'            => 'د.ا',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'JPY' => [
			'name'              => 'Yen',
			'code'              => 'JPY',
			'number'            => 392,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => '¥',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KES' => [
			'name'              => 'Kenyan Shilling',
			'code'              => 'KES',
			'number'            => 404,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'KSh',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KGS' => [
			'name'              => 'Som',
			'code'              => 'KGS',
			'number'            => 417,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'som',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KHR' => [
			'name'              => 'Riel',
			'code'              => 'KHR',
			'number'            => 116,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '៛',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KMF' => [
			'name'              => 'Comoro Franc',
			'code'              => 'KMF',
			'number'            => 174,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Fr',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KPW' => [
			'name'              => 'North Korean Won',
			'code'              => 'KPW',
			'number'            => 408,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₩',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KRW' => [
			'name'              => 'Won',
			'code'              => 'KRW',
			'number'            => 410,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => '₩',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KWD' => [
			'name'              => 'Kuwaiti Dinar',
			'code'              => 'KWD',
			'number'            => 414,
			'precision'         => 3,
			'subunit'           => 1000,
			'symbol'            => 'د.ك',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KYD' => [
			'name'              => 'Cayman Islands Dollar',
			'code'              => 'KYD',
			'number'            => 136,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'KZT' => [
			'name'              => 'Tenge',
			'code'              => 'KZT',
			'number'            => 398,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '〒',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'LAK' => [
			'name'              => 'Kip',
			'code'              => 'LAK',
			'number'            => 418,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₭',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'LBP' => [
			'name'              => 'Lebanese Pound',
			'code'              => 'LBP',
			'number'            => 422,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ل.ل',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'LKR' => [
			'name'              => 'Sri Lanka Rupee',
			'code'              => 'LKR',
			'number'            => 144,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₨',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'LRD' => [
			'name'              => 'Liberian Dollar',
			'code'              => 'LRD',
			'number'            => 430,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'LSL' => [
			'name'              => 'Loti',
			'code'              => 'LSL',
			'number'            => 426,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'L',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'LTL' => [
			'name'              => 'Lithuanian Litas',
			'code'              => 'LTL',
			'number'            => 440,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Lt',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'LVL' => [
			'name'              => 'Latvian Lats',
			'code'              => 'LVL',
			'number'            => 428,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Ls',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'LYD' => [
			'name'              => 'Libyan Dinar',
			'code'              => 'LYD',
			'number'            => 434,
			'precision'         => 3,
			'subunit'           => 1000,
			'symbol'            => 'ل.د',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MAD' => [
			'name'              => 'Moroccan Dirham',
			'code'              => 'MAD',
			'number'            => 504,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'د.م.',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MDL' => [
			'name'              => 'Moldovan Leu',
			'code'              => 'MDL',
			'number'            => 498,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'L',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MGA' => [
			'name'              => 'Malagasy Ariary',
			'code'              => 'MGA',
			'number'            => 969,
			'precision'         => 2,
			'subunit'           => 5,
			'symbol'            => 'Ar',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MKD' => [
			'name'              => 'Denar',
			'code'              => 'MKD',
			'number'            => 807,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ден',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MMK' => [
			'name'              => 'Kyat',
			'code'              => 'MMK',
			'number'            => 104,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'K',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MNT' => [
			'name'              => 'Tugrik',
			'code'              => 'MNT',
			'number'            => 496,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₮',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MOP' => [
			'name'              => 'Pataca',
			'code'              => 'MOP',
			'number'            => 446,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'P',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MRO' => [
			'name'              => 'Ouguiya',
			'code'              => 'MRO',
			'number'            => 478,
			'precision'         => 2,
			'subunit'           => 5,
			'symbol'            => 'UM',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MUR' => [
			'name'              => 'Mauritius Rupee',
			'code'              => 'MUR',
			'number'            => 480,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₨',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MVR' => [
			'name'              => 'Rufiyaa',
			'code'              => 'MVR',
			'number'            => 462,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'MVR',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MWK' => [
			'name'              => 'Kwacha',
			'code'              => 'MWK',
			'number'            => 454,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'MK',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MXN' => [
			'name'              => 'Mexican Peso',
			'code'              => 'MXN',
			'number'            => 484,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MYR' => [
			'name'              => 'Malaysian Ringgit',
			'code'              => 'MYR',
			'number'            => 458,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'RM',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'MZN' => [
			'name'              => 'Mozambique Metical',
			'code'              => 'MZN',
			'number'            => 943,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'MTn',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'NAD' => [
			'name'              => 'Namibia Dollar',
			'code'              => 'NAD',
			'number'            => 516,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'NGN' => [
			'name'              => 'Naira',
			'code'              => 'NGN',
			'number'            => 566,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₦',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'NIO' => [
			'name'              => 'Cordoba Oro',
			'code'              => 'NIO',
			'number'            => 558,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'C$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'NOK' => [
			'name'              => 'Norwegian Krone',
			'code'              => 'NOK',
			'number'            => 578,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'kr',
			'position'          => 'after',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'NPR' => [
			'name'              => 'Nepalese Rupee',
			'code'              => 'NPR',
			'number'            => 524,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₨',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'NZD' => [
			'name'              => 'New Zealand Dollar',
			'code'              => 'NZD',
			'number'            => 554,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'OMR' => [
			'name'              => 'Rial Omani',
			'code'              => 'OMR',
			'number'            => 512,
			'precision'         => 3,
			'subunit'           => 1000,
			'symbol'            => 'ر.ع.',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'PAB' => [
			'name'              => 'Balboa',
			'code'              => 'PAB',
			'number'            => 590,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'B/.',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'PEN' => [
			'name'              => 'Sol',
			'code'              => 'PEN',
			'number'            => 604,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'S/',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'PGK' => [
			'name'              => 'Kina',
			'code'              => 'PGK',
			'number'            => 598,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'K',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'PHP' => [
			'name'              => 'Philippine Peso',
			'code'              => 'PHP',
			'number'            => 608,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₱',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'PKR' => [
			'name'              => 'Pakistan Rupee',
			'code'              => 'PKR',
			'number'            => 586,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₨',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'PLN' => [
			'name'              => 'Zloty',
			'code'              => 'PLN',
			'number'            => 985,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'zł',
			'position'          => 'after',
			'decimalSeparator'  => ',',
			'thousandSeparator' => ' ',
		],

		'PYG' => [
			'name'              => 'Guarani',
			'code'              => 'PYG',
			'number'            => 600,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => '₲',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'QAR' => [
			'name'              => 'Qatari Rial',
			'code'              => 'QAR',
			'number'            => 634,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ر.ق',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'RON' => [
			'name'              => 'New Romanian Leu',
			'code'              => 'RON',
			'number'            => 946,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Lei',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'RSD' => [
			'name'              => 'Serbian Dinar',
			'code'              => 'RSD',
			'number'            => 941,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'РСД',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'RUB' => [
			'name'              => 'Russian Ruble',
			'code'              => 'RUB',
			'number'            => 643,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₽',
			'position'          => 'after',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'RWF' => [
			'name'              => 'Rwanda Franc',
			'code'              => 'RWF',
			'number'            => 646,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'FRw',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SAR' => [
			'name'              => 'Saudi Riyal',
			'code'              => 'SAR',
			'number'            => 682,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ر.س',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SBD' => [
			'name'              => 'Solomon Islands Dollar',
			'code'              => 'SBD',
			'number'            => 90,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SCR' => [
			'name'              => 'Seychelles Rupee',
			'code'              => 'SCR',
			'number'            => 690,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₨',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SDG' => [
			'name'              => 'Sudanese Pound',
			'code'              => 'SDG',
			'number'            => 938,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '£',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SEK' => [
			'name'              => 'Swedish Krona',
			'code'              => 'SEK',
			'number'            => 752,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'kr',
			'position'          => 'after',
			'decimalSeparator'  => ',',
			'thousandSeparator' => ' ',
		],

		'SGD' => [
			'name'              => 'Singapore Dollar',
			'code'              => 'SGD',
			'number'            => 702,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SHP' => [
			'name'              => 'Saint Helena Pound',
			'code'              => 'SHP',
			'number'            => 654,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '£',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SLL' => [
			'name'              => 'Leone',
			'code'              => 'SLL',
			'number'            => 694,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Le',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SOS' => [
			'name'              => 'Somali Shilling',
			'code'              => 'SOS',
			'number'            => 706,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Sh',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SRD' => [
			'name'              => 'Surinam Dollar',
			'code'              => 'SRD',
			'number'            => 968,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SSP' => [
			'name'              => 'South Sudanese Pound',
			'code'              => 'SSP',
			'number'            => 728,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '£',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'STD' => [
			'name'              => 'Dobra',
			'code'              => 'STD',
			'number'            => 678,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Db',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SVC' => [
			'name'              => 'El Salvador Colon',
			'code'              => 'SVC',
			'number'            => 222,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₡',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SYP' => [
			'name'              => 'Syrian Pound',
			'code'              => 'SYP',
			'number'            => 760,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '£S',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'SZL' => [
			'name'              => 'Lilangeni',
			'code'              => 'SZL',
			'number'            => 748,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'E',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'THB' => [
			'name'              => 'Baht',
			'code'              => 'THB',
			'number'            => 764,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '฿',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'TJS' => [
			'name'              => 'Somoni',
			'code'              => 'TJS',
			'number'            => 972,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ЅМ',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'TMT' => [
			'name'              => 'Turkmenistan New Manat',
			'code'              => 'TMT',
			'number'            => 934,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'T',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'TND' => [
			'name'              => 'Tunisian Dinar',
			'code'              => 'TND',
			'number'            => 788,
			'precision'         => 3,
			'subunit'           => 1000,
			'symbol'            => 'د.ت',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'TOP' => [
			'name'              => 'Pa’anga',
			'code'              => 'TOP',
			'number'            => 776,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'T$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'TRY' => [
			'name'              => 'Turkish Lira',
			'code'              => 'TRY',
			'number'            => 949,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₺',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'TTD' => [
			'name'              => 'Trinidad and Tobago Dollar',
			'code'              => 'TTD',
			'number'            => 780,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'TWD' => [
			'name'              => 'New Taiwan Dollar',
			'code'              => 'TWD',
			'number'            => 901,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'TZS' => [
			'name'              => 'Tanzanian Shilling',
			'code'              => 'TZS',
			'number'            => 834,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Sh',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'UAH' => [
			'name'              => 'Hryvnia',
			'code'              => 'UAH',
			'number'            => 980,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '₴',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'UGX' => [
			'name'              => 'Uganda Shilling',
			'code'              => 'UGX',
			'number'            => 800,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'USh',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'USD' => [
			'name'              => 'US Dollar',
			'code'              => 'USD',
			'number'            => 840,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'UYU' => [
			'name'              => 'Peso Uruguayo',
			'code'              => 'UYU',
			'number'            => 858,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'UZS' => [
			'name'              => 'Uzbekistan Sum',
			'code'              => 'UZS',
			'number'            => 860,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => null,
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'VEF' => [
			'name'              => 'Bolivar',
			'code'              => 'VEF',
			'number'            => 937,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'Bs F',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'VND' => [
			'name'              => 'Dong',
			'code'              => 'VND',
			'number'            => 704,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => '₫',
			'position'          => 'before',
			'decimalSeparator'  => ',',
			'thousandSeparator' => '.',
		],

		'VUV' => [
			'name'              => 'Vatu',
			'code'              => 'VUV',
			'number'            => 548,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Vt',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'WST' => [
			'name'              => 'Tala',
			'code'              => 'WST',
			'number'            => 882,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'T',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'XAF' => [
			'name'              => 'CFA Franc BEAC',
			'code'              => 'XAF',
			'number'            => 950,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Fr',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'XAG' => [
			'name'              => 'Silver',
			'code'              => 'XAG',
			'number'            => 961,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'oz t',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'XAU' => [
			'name'              => 'Gold',
			'code'              => 'XAU',
			'number'            => 959,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'oz t',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'XCD' => [
			'name'              => 'East Caribbean Dollar',
			'code'              => 'XCD',
			'number'            => 951,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'XDR' => [
			'name'              => 'SDR (Special Drawing Right)',
			'code'              => 'XDR',
			'number'            => 960,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'SDR',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'XOF' => [
			'name'              => 'CFA Franc BCEAO',
			'code'              => 'XOF',
			'number'            => 952,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Fr',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'XPF' => [
			'name'              => 'CFP Franc',
			'code'              => 'XPF',
			'number'            => 953,
			'precision'         => 0,
			'subunit'           => 1,
			'symbol'            => 'Fr',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'YER' => [
			'name'              => 'Yemeni Rial',
			'code'              => 'YER',
			'number'            => 886,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '﷼',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ZAR' => [
			'name'              => 'Rand',
			'code'              => 'ZAR',
			'number'            => 710,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'R',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ZMW' => [
			'name'              => 'Zambian Kwacha',
			'code'              => 'ZMW',
			'number'            => 967,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => 'ZK',
			'position'          => 'after',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],

		'ZWL' => [
			'name'              => 'Zimbabwe Dollar',
			'code'              => 'ZWL',
			'number'            => 932,
			'precision'         => 2,
			'subunit'           => 100,
			'symbol'            => '$',
			'position'          => 'before',
			'decimalSeparator'  => '.',
			'thousandSeparator' => ',',
		],
	);

	return apply_filters( 'wpcp_currency_config', $config );
}

/**
 * since 1.0.0
 *
 * @param string $currency
 *
 * @return mixed
 */
function eaccounting_get_currency_config( $currency = 'USD' ) {
	$data = eaccounting_get_global_currencies();

	return array_key_exists( $currency, $data ) ? $data[ $currency ] : $data['USD'];
}

/**
 * Get payment methods
 * since 1.0.0
 * @return array
 */
function eaccounting_get_payment_methods() {
	return apply_filters( 'eaccounting_payment_methods', [
		'cash'          => __( 'Cash', 'wp-ever-accounting' ),
		'bank_transfer' => __( 'Bank Transfer', 'wp-ever-accounting' ),
		'check'         => __( 'Cheque', 'wp-ever-accounting' ),
	] );
}

