/**
 * Internal dependencies
 */

export const CURRENCIES_LOADING = 'CURRENCIES_LOADING';
export const CURRENCIES_LOADED = 'CURRENCIES_LOADED';
export const CURRENCIES_FAILED = 'CURRENCIES_FAILED';
export const CURRENCIES_SET_SELECTED = 'CURRENCIES_SET_SELECTED';
export const CURRENCIES_SET_ALL_SELECTED = 'CURRENCIES_SET_ALL_SELECTED';
export const CURRENCIES_ITEM_SAVING = 'CURRENCIES_ITEM_SAVING';
export const CURRENCIES_ITEM_FAILED = 'CURRENCIES_ITEM_FAILED';
export const CURRENCIES_ITEM_SAVED = 'CURRENCIES_ITEM_SAVED';
export const CURRENCIES_ITEM_ADDED = 'CURRENCIES_ITEM_ADDED';
