/**
 * Internal dependencies
 */

export const PAYMENTS_LOADING = 'PAYMENTS_LOADING';
export const PAYMENTS_LOADED = 'PAYMENTS_LOADED';
export const PAYMENTS_FAILED = 'PAYMENTS_FAILED';
export const PAYMENTS_SET_SELECTED = 'PAYMENTS_SET_SELECTED';
export const PAYMENTS_SET_ALL_SELECTED = 'PAYMENTS_SET_ALL_SELECTED';
export const PAYMENTS_ITEM_SAVING = 'PAYMENTS_ITEM_SAVING';
export const PAYMENTS_ITEM_FAILED = 'PAYMENTS_ITEM_FAILED';
export const PAYMENTS_ITEM_SAVED = 'PAYMENTS_ITEM_SAVED';
export const PAYMENTS_DISPLAY_SET = 'PAYMENTS_DISPLAY_SET';
