name: Coding Standards
on:
    push:
        branches:
            - develop
            - master
    pull_request:
        branches:
            - develop

jobs:
    phpcs:
        name: PHP coding standards
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set PHP version
              uses: shivammathur/setup-php@v1
              with:
                  php-version: '7.3'
                  coverage: none
            - name: composer install
              run: composer install
            - name: PHPCS check
              uses: chekalsky/phpcs-action@v1
              with:
                  phpcs_bin_path: './vendor/bin/phpcs .'
