name: Run PHP unit tests
on: [push, pull_request]

jobs:
    test:
        name: PHP ${{ matrix.php }} WP ${{ matrix.wp }}
        timeout-minutes: 15
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.0', '7.1', '7.2', '7.3', '7.4']
                wp: ['latest']
                include:
                    - wp: nightly
                      php: '7.4'
                    - wp: '5.5'
                      php: 7.2
                    - wp: '5.4'
                      php: 7.2
        services:
            database:
                image: mysql:5.6
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer
                  extensions: mysql
                  coverage: none

            - name: Setup token
              run: composer config -g github-oauth.github.com ${{ secrets.ACCESS_TOKEN }}

            - name: Configure git
              run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
              env:
                  TOKEN: ${{ secrets.ACCESS_TOKEN }}

            - name: Tool versions
              run: |
                  php --version
                  composer --version
            - name: Get cached composer directories
              uses: actions/cache@v2
              with:
                  path: |
                      ./packages
                      ./vendor
                  key: ${{ runner.os }}-${{ hashFiles('./composer.lock') }}

            - name: Setup and install composer
              run: composer install

            - name: Init DB and WP
              run: ./bin/install-wp-tests.sh eaccounting_tests root root 127.0.0.1 ${{ matrix.wp }}

            - name: Run tests
              run: ./vendor/bin/phpunit -c ./phpunit.xml
